### ISSUE TITLE
Number of dims don't match in permute error

### ISSUE THREAD

**Issue by MustafaUysal160207077** [zylo117/Yet-Another-EfficientDet-Pytorch#142]
Hi,
I've been running this repo one video. I don't use CUDA. Here is the code I've tried.
# Author: Zylo117

```
"""
Simple Inference Script of EfficientDet-Pytorch
"""
import time
import glob
import torch
from torch.backends import cudnn

from backbone import EfficientDetBackbone
import cv2
import numpy as np

from efficientdet.utils import BBoxTransform, ClipBoxes
from utils.utils import preprocess, invert_affine, postprocess, preprocess_single_image

compound_coef = 0
force_input_size = None  # set None to use default size
img_path = 'C:/Users/mustafa/Desktop/bitincesil/frame4120.jpg'

# replace this part with your project's anchor config
anchor_ratios = [(1.0, 1.0), (1.4, 0.7), (0.7, 1.4)]
anchor_scales = [2 ** 0, 2 ** (1.0 / 3.0), 2 ** (2.0 / 3.0)]

threshold = 0.2
iou_threshold = 0.2

use_cuda = False
use_float16 = False
cudnn.fastest = True
cudnn.benchmark = True

obj_list = ['person', 'bicycle', 'car', 'motorcycle', 'airplane', 'bus', 'train', 'truck', 'boat', 'traffic light',
            'fire hydrant', '', 'stop sign', 'parking meter', 'bench', 'bird', 'cat', 'dog', 'horse', 'sheep',
            'cow', 'elephant', 'bear', 'zebra', 'giraffe', '', 'backpack', 'umbrella', '', '', 'handbag', 'tie',
            'suitcase', 'frisbee', 'skis', 'snowboard', 'sports ball', 'kite', 'baseball bat', 'baseball glove',
            'skateboard', 'surfboard', 'tennis racket', 'bottle', '', 'wine glass', 'cup', 'fork', 'knife', 'spoon',
            'bowl', 'banana', 'apple', 'sandwich', 'orange', 'broccoli', 'carrot', 'hot dog', 'pizza', 'donut',
            'cake', 'chair', 'couch', 'potted plant', 'bed', '', 'dining table', '', '', 'toilet', '', 'tv',
            'laptop', 'mouse', 'remote', 'keyboard', 'cell phone', 'microwave', 'oven', 'toaster', 'sink',
            'refrigerator', '', 'book', 'clock', 'vase', 'scissors', 'teddy bear', 'hair drier',
            'toothbrush']


   

def display(preds, imgs,  count, imshow=True, imwrite=False):
    
    for i in range(len(imgs)):
        if len(preds[i]['rois']) == 0:
            continue

        for j in range(len(preds[i]['rois'])):
            (x1, y1, x2, y2) = preds[i]['rois'][j].astype(np.int)
            cv2.rectangle(imgs[i], (x1, y1), (x2, y2), (255, 255, 0), 2)
            obj = obj_list[preds[i]['class_ids'][j]]
            score = float(preds[i]['scores'][j])

            cv2.putText(imgs[i], '{}, {:.3f}'.format(obj, score),
                        (x1, y1 + 10), cv2.FONT_HERSHEY_SIMPLEX, 0.5,
                        (255, 255, 0), 1)

        if imshow:
            cv2.imshow('img', imgs[i])
            cv2.waitKey(0)

        if imwrite:
            #cv2.imwrite('output/frame%d.jpg', imgs[i])
            cv2.imwrite("output/frame%d.jpg" % count, imgs[i]) 

# tf bilinear interpolation is different from any other's, just make do
input_sizes = [512, 640, 768, 896, 1024, 1280, 1280, 1536]
input_size = input_sizes[compound_coef] if force_input_size is None else force_input_size
count = 0


        
video_path = "t.mp4" # or camera id
vid = cv2.VideoCapture(video_path)

model = EfficientDetBackbone(compound_coef=compound_coef, num_classes=len(obj_list),
                                 ratios=anchor_ratios, scales=anchor_scales)
model.load_state_dict(torch.load(f'weights/efficientdet-d{compound_coef}.pth'))
model.requires_grad_(False)
model.eval()

while vid.grab():
    
    ret, frame = vid.retrieve()
    if not ret:
        break

    # BGR 2 RGB
    frame = cv2.cvtColor(frame, cv2.COLOR_BGR2RGB)

    # preprocss for single image
    ori_img, framed_img, framed_meta = preprocess_single_image(frame, max_size=input_size)
    
    #  detection
    inference_start_time = time.time()
    with torch.no_grad():
        
        x = torch.stack([torch.from_numpy(fi) for fi in framed_img], 0)
        x = x.to(torch.float32 if not use_float16 else torch.float16).permute(0, 3, 1, 2)

        features, regression, classification, anchors = model(x)

        regressBoxes = BBoxTransform()
        clipBoxes = ClipBoxes()

        out = postprocess(x,
                          anchors, regression, classification,
                          regressBoxes, clipBoxes,
                          threshold, iou_threshold)
    inference_end_time = time.time()
    #logging.info("\t Inference time: %s ", datetime.timedelta(seconds=inference_end_time - inference_start_time))

    # detection over

    # log FPS on frame
    ...


    # get detection bbox
    out = invert_affine([framed_meta], out)

    # reverse to BGR
    frame = cv2.cvtColor(frame, cv2.COLOR_RGB2BGR)

    # draw bbox on frame and display
    display(out[0], frame, imwrite=False)
    if cv2.waitKey(1) & 0xFF == ord('q'):
        break

```

This is the error line
` x = x.to(torch.float32 if not use_float16 else torch.float16).permute(0, 3, 1, 2)`
And I've defined `preprocess_single_image` as :

```
def preprocess_single_image(img, max_size=512, mean=(0.406, 0.456, 0.485), std=(0.225, 0.224, 0.229)):
    normalized_img = (img / 255 - mean) / std
    img_meta = aspectaware_resize_padding(img[..., ::-1], max_size, max_size,
                                            means=None) 
    
    framed_img = img_meta[0] 
    framed_meta = img_meta[1:]

    return normalized_img, framed_img, framed_meta
```

**Comment by zylo117** [comment]
so, what's the error exactly?

**Comment by MustafaUysal160207077** [comment]
This is the whole error message:
```
Traceback (most recent call last):
  File "videodeneme.py", line 105, in <module>
    x = x.to(torch.float32 if not use_float16 else torch.float16).permute(0, 3,
1, 2)
RuntimeError: number of dims don't match in permute
```

**Comment by zylo117** [comment]
add `x = x.unsqeeze(0)` before line105

**Comment by MustafaUysal160207077** [comment]
Type of `x` is `torch.Tensor ` but I see this error

```
<class 'torch.Tensor'>
Traceback (most recent call last):
  File "videodeneme.py", line 106, in <module>
    x = x.unsqeeze(0)
AttributeError: 'Tensor' object has no attribute 'unsqeeze'
```

**Comment by zylo117** [comment]
oh, typo, 
x = x.unsqueeze(0)

**Comment by MustafaUysal160207077** [comment]
> oh, typo,
> x = x.unsqueeze(0)

Thanks a lot, could you also share `preprocess_video` method. I've tried to use `preprocess_single_image` but it's caused an error.

**Comment by zylo117** [comment]
> > oh, typo,
> > x = x.unsqueeze(0)
> 
> Thanks a lot, could you also share `preprocess_video` method. I've tried to use `preprocess_single_image` but it's caused an error.

Hi, there are two pull requsests about processing video, I might merge them when they complete their changes. In the mean time, you can solve it by referring to their work, or wait for a update.

**Comment by MustafaUysal160207077** [comment]
Thanks.
