### ISSUE TITLE
CUDA out of memory

### ISSUE THREAD

**Issue by eduardohem** [zylo117/Yet-Another-EfficientDet-Pytorch#146]
[Error] Traceback (most recent call last):
  File "train.py", line 227, in train
    cls_loss, reg_loss = model(imgs, annot, obj_list=params.obj_list)
  File "/home/itandroids/Desktop/eficientedet/zylo/lib/python3.6/site-packages/torch/nn/modules/module.py", line 532, in __call__
    result = self.forward(*input, **kwargs)
  File "train.py", line 76, in forward
    _, regression, classification, anchors = self.model(imgs)
  File "/home/itandroids/Desktop/eficientedet/zylo/lib/python3.6/site-packages/torch/nn/modules/module.py", line 532, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/itandroids/Desktop/eficientedet/zylo/backbone.py", line 65, in forward
    _, p3, p4, p5 = self.backbone_net(inputs)
  File "/home/itandroids/Desktop/eficientedet/zylo/lib/python3.6/site-packages/torch/nn/modules/module.py", line 532, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/itandroids/Desktop/eficientedet/zylo/efficientdet/model.py", line 412, in forward
    x = block(x, drop_connect_rate=drop_connect_rate)
  File "/home/itandroids/Desktop/eficientedet/zylo/lib/python3.6/site-packages/torch/nn/modules/module.py", line 532, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/itandroids/Desktop/eficientedet/zylo/efficientnet/model.py", line 78, in forward
    x = self._bn0(x)
  File "/home/itandroids/Desktop/eficientedet/zylo/lib/python3.6/site-packages/torch/nn/modules/module.py", line 532, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/itandroids/Desktop/eficientedet/zylo/lib/python3.6/site-packages/torch/nn/modules/batchnorm.py", line 107, in forward
    exponential_average_factor, self.eps)
  File "/home/itandroids/Desktop/eficientedet/zylo/lib/python3.6/site-packages/torch/nn/functional.py", line 1670, in batch_norm
    training, momentum, eps, torch.backends.cudnn.enabled
RuntimeError: CUDA out of memory. Tried to allocate 1.72 GiB (GPU 0; 10.91 GiB total capacity; 7.71 GiB already allocated; 209.94 MiB free; 9.75 GiB reserved in total by PyTorch)

**Comment by zylo117** [comment]
reduce batchsize or switch to a smaller backbone

**Comment by eduardohem** [comment]
Worked with batchsize 2 , but I am thinking that's very under the regular size.

**Comment by Xudangliatiger** [comment]
Hello, it is really a nice work! 
How many GPUs should I have that I can train a complete EfficientDet.

**Comment by zylo117** [comment]
It depends on your vram size. You can check that up on readme. The training vram is about 3 times larger than the inference's
