### ISSUE TITLE
coco eval bug

### ISSUE THREAD

**Issue by rvandeghen** [zylo117/Yet-Another-EfficientDet-Pytorch#166]
Hello,

I have a problem when i try to evaluate with coco:

`Traceback (most recent call last):
  File "/home/renaud/anaconda3/envs/tfe/lib/python3.6/site-packages/numpy/core/function_base.py", line 117, in linspace
    num = operator.index(num)
TypeError: 'numpy.float64' object cannot be interpreted as an integer

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "coco_eval.py", line 168, in <module>
    _eval(coco_gt, image_ids, f'{SET_NAME}_bbox_results.json')
  File "coco_eval.py", line 138, in _eval
    coco_eval = COCOeval(coco_gt, coco_pred, 'bbox')
  File "/home/renaud/anaconda3/envs/tfe/lib/python3.6/site-packages/pycocotools/cocoeval.py", line 76, in __init__
    self.params = Params(iouType=iouType) # parameters
  File "/home/renaud/anaconda3/envs/tfe/lib/python3.6/site-packages/pycocotools/cocoeval.py", line 527, in __init__
    self.setDetParams()
  File "/home/renaud/anaconda3/envs/tfe/lib/python3.6/site-packages/pycocotools/cocoeval.py", line 507, in setDetParams
    self.iouThrs = np.linspace(.5, 0.95, np.round((0.95 - .5) / .05) + 1, endpoint=True)
  File "<__array_function__ internals>", line 6, in linspace
  File "/home/renaud/anaconda3/envs/tfe/lib/python3.6/site-packages/numpy/core/function_base.py", line 121, in linspace
    .format(type(num)))
TypeError: object of type <class 'numpy.float64'> cannot be safely interpreted as an integer.`

numpy version: 1.18.1

**Comment by llllliu1** [comment]
Hello, I met the same problem , have you solved it?

**Comment by rvandeghen** [comment]
@llllliu1 Hello,

Yes I solved this but cannot exactly remember what I have done.

I know I changed something in

`self.iouThrs = np.linspace(.5, 0.95, np.round((0.95 - .5) / .05) + 1, endpoint=True)`

Probably that:

`self.iouThrs = np.linspace(.5, 0.95, int(np.round((0.95 - .5) / .05)) + 1, endpoint=True)`

Let me know if it worked so I can check further if needed

**Comment by lanshiyinging** [comment]
> Hello, I met the same problem , have you solved it?

change the version of Numpy to 1.17.0
