### ISSUE TITLE
evaluation error

### ISSUE THREAD

**Issue by kaishijeng** [zylo117/Yet-Another-EfficientDet-Pytorch#18]
When I use your pretrained d0 weight and run evaluation script as below and got an error:
python coco_eval.py -c 0 -w weights/efficientdet-d0.pth

running coco-style evaluation on project coco, weights weights/efficientdet-d0.pth...
loading annotations into memory...
Done (t=0.28s)
creating index...
index created!
Loading and preparing results...
Traceback (most recent call last):
  File "coco_eval.py", line 146, in <module>
    eval(coco_gt, image_ids, f'{SET_NAME}_bbox_results.json')
  File "coco_eval.py", line 114, in eval
    coco_pred = coco_gt.loadRes(pred_json_path)
  File "/home/henry/miniconda3/env/test/lib/python3.6/site-packages/pycocotools/coco.py", line 317, in loadRes
    'Results do not correspond to current coco set'
AssertionError: Results do not correspond to current coco set

**Comment by kaishijeng** [comment]
Ignore error in the previous Jira. The new error is below after I delete existing val2017_bbox_results.json and rerun eval script::

Traceback (most recent call last):
  File "/home/henry/.local/lib/python3.6/site-packages/numpy/core/function_base.py", line 117, in linspace
    num = operator.index(num)
TypeError: 'numpy.float64' object cannot be interpreted as an integer

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "coco_eval.py", line 146, in <module>
    eval(coco_gt, image_ids, f'{SET_NAME}_bbox_results.json')
  File "coco_eval.py", line 118, in eval
    coco_eval = COCOeval(coco_gt, coco_pred, 'bbox')
  File "/home/henry/miniconda3/envs/remnav/lib/python3.6/site-packages/pycocotools/cocoeval.py", line 76, in __init__
    self.params = Params(iouType=iouType) # parameters
  File "/home/henry/miniconda3/envs/remnav/lib/python3.6/site-packages/pycocotools/cocoeval.py", line 527, in __init__
    self.setDetParams()
  File "/home/henry/miniconda3/envs/remnav/lib/python3.6/site-packages/pycocotools/cocoeval.py", line 507, in setDetParams
    self.iouThrs = np.linspace(.5, 0.95, np.round((0.95 - .5) / .05) + 1, endpoint=True)
  File "<__array_function__ internals>", line 6, in linspace
  File "/home/henry/.local/lib/python3.6/site-packages/numpy/core/function_base.py", line 121, in linspace
    .format(type(num)))
TypeError: object of type <class 'numpy.float64'> cannot be safely interpreted as an integer.

**Comment by zylo117** [comment]
It looks like a COCOAPI error, can you share you pycocotools version?
Mine is 2.0.0. This api is really buggy.

**Comment by kaishijeng** [comment]
Never mind. I modify pycocotools as follows and it works now.

np.round((0.95 - .5) / .05) --> int(np.round((0.95 - .5) / .05))
