### ISSUE TITLE
使用d4-6训练时报错RuntimeError: Assertion `!input->is_empty() && THCTensor_(nDimensionLegacyNoScalars)(state, input) == 4

### ISSUE THREAD

**Issue by bsysman** [zylo117/Yet-Another-EfficientDet-Pytorch#188]
RuntimeError: Caught RuntimeError in replica 0 on device 0.
Original Traceback (most recent call last):
  File "/usr/local/python/lib/python3.6/site-packages/torch/nn/parallel/parallel_apply.py", line 60, in _worker
    output = module(*input, **kwargs)
  File "/usr/local/python/lib/python3.6/site-packages/torch/nn/modules/module.py", line 532, in __call__
    result = self.forward(*input, **kwargs)
  File "train.py", line 75, in forward
    _, regression, classification, anchors = self.model(imgs)
  File "/usr/local/python/lib/python3.6/site-packages/torch/nn/modules/module.py", line 532, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/cang-ai-ei/soft/Yet-Another-EfficientDet-Pytorch-master/backbone.py", line 65, in forward
    _, p3, p4, p5 = self.backbone_net(inputs)
  File "/usr/local/python/lib/python3.6/site-packages/torch/nn/modules/module.py", line 532, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/cang-ai-ei/soft/Yet-Another-EfficientDet-Pytorch-master/efficientdet/model.py", line 412, in forward
    x = block(x, drop_connect_rate=drop_connect_rate)
  File "/usr/local/python/lib/python3.6/site-packages/torch/nn/modules/module.py", line 532, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/cang-ai-ei/soft/Yet-Another-EfficientDet-Pytorch-master/efficientnet/model.py", line 81, in forward
    x = self._depthwise_conv(x)
  File "/usr/local/python/lib/python3.6/site-packages/torch/nn/modules/module.py", line 532, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/cang-ai-ei/soft/Yet-Another-EfficientDet-Pytorch-master/efficientnet/utils_extra.py", line 51, in forward
    x = self.conv(x)
  File "/usr/local/python/lib/python3.6/site-packages/torch/nn/modules/module.py", line 532, in __call__
    result = self.forward(*input, **kwargs)
  File "/usr/local/python/lib/python3.6/site-packages/torch/nn/modules/conv.py", line 345, in forward
    return self.conv2d_forward(input, self.weight)
  File "/usr/local/python/lib/python3.6/site-packages/torch/nn/modules/conv.py", line 342, in conv2d_forward
    self.padding, self.dilation, self.groups)
RuntimeError: Assertion `!input->is_empty() && THCTensor_(nDimensionLegacyNoScalars)(state, input) == 4' failed.  at /pytorch/aten/src/THCUNN/generic/SpatialDepthwiseConvolution.cu:19

**Comment by zylo117** [comment]
What's your torch version? This repo is tested on torch 1.4.0 and it works.

**Comment by bsysman** [comment]
已经升级为1.4，但是同样报错，训练d1-3整除

**Comment by zylo117** [comment]
Is it OOM? Try reducing batchsize to 1, and monitor the vram during training.

**Comment by bsysman** [comment]
batchsize 改为1同样的错误

**Comment by durui-12315** [comment]
我之前用３个ＧＰＵ训练，保存模型后停止训练；然后再用２个ＧＰＵ训练之前保存的模型后，就报这个错误，然后再用原来额３个ＧＰＵ训练就没有这个错误了。@bsysman　这个错误你解决了么？
