### ISSUE TITLE
OSError: [Errno 12] Cannot allocate memory (during training)

### ISSUE THREAD

**Issue by HesperX** [zylo117/Yet-Another-EfficientDet-Pytorch#191]
Hello, thank you for this excellent work.
When I run your code `train.py`,  an error happen after several epochs:
```
~/Yet-Another-EfficientDet-Pytorch$ python train.py -c 0 --batch_size 32 --n$
m_workers 16 --val_interval 250
loading annotations into memory...
Done (t=17.36s)
creating index...
index created!
loading annotations into memory...
Done (t=0.62s)
creating index...
index created!
[Info] initializing weights...
Step: 30. Epoch: 0/500. Iteration: 31/31. Cls loss: 102716.83594. Reg loss: 1.37039. Total loss: 10271
Val. Epoch: 0/500. Classification loss: 15382.30692. Regression loss: 0.96920. Total loss: 15383.27612
Step: 61. Epoch: 1/500. Iteration: 31/31. Cls loss: 11970.64941. Reg loss: 1.10038. Total loss: 11971.
Step: 92. Epoch: 2/500. Iteration: 31/31. Cls loss: 8047.87695. Reg loss: 0.87966. Total loss: 8048.75
  0%|                                                                          | 0/31 [00:00<?, ?it/s]
Traceback (most recent call last):
  File "train.py", line 338, in <module>
    train(opt)
  File "train.py", line 206, in train
    for iter, data in enumerate(progress_bar):
  File "/home/yichen/miniconda3/envs/EfficientDet/lib/python3.6/site-packages/tqdm/std.py", line 1127,
 in __iter__
    for obj in iterable:
  File "/home/yichen/miniconda3/envs/EfficientDet/lib/python3.6/site-packages/torch/utils/data/datalo$der.py", line 279, in __iter__
    return _MultiProcessingDataLoaderIter(self)
  File "/home/yichen/miniconda3/envs/EfficientDet/lib/python3.6/site-packages/torch/utils/data/datalo$der.py", line 719, in __init__
    w.start()
  File "/home/yichen/miniconda3/envs/EfficientDet/lib/python3.6/multiprocessing/process.py", line 105, in start
    self._popen = self._Popen(self)
  File "/home/yichen/miniconda3/envs/EfficientDet/lib/python3.6/multiprocessing/context.py", line 223, in _Popen
    return _default_context.get_context().Process._Popen(process_obj)
  File "/home/yichen/miniconda3/envs/EfficientDet/lib/python3.6/multiprocessing/context.py", line 277, in _Popen
    return Popen(process_obj)  File "/home/yichen/miniconda3/envs/EfficientDet/lib/python3.6/multiprocessing/popen_fork.py", line 19, in __init__
    self._launch(process_obj)  File "/home/yichen/miniconda3/envs/EfficientDet/lib/python3.6/multiprocessing/popen_fork.py", line 66, in _launch
    self.pid = os.fork()
OSError: [Errno 12] Cannot allocate memory
```
I use 8 GPUs for training and set the batch size 32, num workers 16. My environment is python 3.6 and pytorch 1.4.0.

I am not sure what is the memory requirement for training but I have 40GB so I think it's enough.

If you want to replicate this error, I suggest you set the dataset length less, which will save a lot of time.
```

    def __len__(self):
        return 1000
        # return len(self.image_ids)
```

Thank you very much.

**Comment by zylo117** [comment]
it could be system limit. try reducing num workers

**Comment by HesperX** [comment]
I reduced num workers to 8. And I think it's OK now. Thank you very much.
