### ISSUE TITLE
D4  RuntimeError: CUDA out of memory. 

### ISSUE THREAD

**Issue by XXSSOTA** [zylo117/Yet-Another-EfficientDet-Pytorch#208]
Can D4 be trained on 4 gpus GeForce RTX 2080? Batch_size 4, RuntimeError: CUDA out of memory.  A GPU can't train an image？

**Comment by XXSSOTA** [comment]
[Error] Traceback (most recent call last):
  File "train.py", line 227, in train
    cls_loss, reg_loss = model(imgs, annot, obj_list=params.obj_list)
  File "/usr/local/lib/python3.7/site-packages/torch/nn/modules/module.py", line 541, in __call__
    result = self.forward(*input, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/torch/nn/parallel/data_parallel.py", line 152, in forward
    outputs = self.parallel_apply(replicas, inputs, kwargs)
  File "/usr/local/lib/python3.7/site-packages/torch/nn/parallel/data_parallel.py", line 162, in parallel_apply
    return parallel_apply(replicas, inputs, kwargs, self.device_ids[:len(replicas)])
  File "/usr/local/lib/python3.7/site-packages/torch/nn/parallel/parallel_apply.py", line 85, in parallel_apply
    output.reraise()
  File "/usr/local/lib/python3.7/site-packages/torch/_utils.py", line 385, in reraise
    raise self.exc_type(msg)
RuntimeError: Caught RuntimeError in replica 0 on device 0.
Original Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/torch/nn/parallel/parallel_apply.py", line 60, in _worker
    output = module(*input, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/torch/nn/modules/module.py", line 541, in __call__
    result = self.forward(*input, **kwargs)
  File "train.py", line 81, in forward
    cls_loss, reg_loss = self.criterion(classification, regression, anchors, annotations)
  File "/usr/local/lib/python3.7/site-packages/torch/nn/modules/module.py", line 541, in __call__
    result = self.forward(*input, **kwargs)
  File "/ProjectRoot/zhaolei/project/image_analyse/Yet-Another-EfficientDet-Pytorch/efficientdet/loss.py", line 86, in forward
    alpha_factor = torch.ones_like(targets) * alpha
RuntimeError: CUDA out of memory. Tried to allocate 274.00 MiB (GPU 0; 10.73 GiB total capacity; 9.03 GiB already allocated; 239.56 MiB free; 593.52 MiB cached)

**Comment by HesperX** [comment]
I meet the same problem. Did you solve it?

**Comment by Ronald-Kray** [comment]
@XXSSOTA have you solved these issues?
