### ISSUE TITLE
Runtime Error: CUDA out of memory

### ISSUE THREAD

**Issue by singlautsav** [zylo117/Yet-Another-EfficientDet-Pytorch#244]
I am training custom dataset, and I am using colab. Following is the error that is bugging me now.

`[Info] loaded weights: efficientdet-d1_18_30500.pth, resuming checkpoint from step: 30500
 17% 278/1679 [17:56<3:04:18,  7.89s/it][Error] Traceback (most recent call last):
  File "train.py", line 227, in train
    cls_loss, reg_loss = model(imgs, annot, obj_list=params.obj_list)
  File "/usr/local/lib/python3.6/dist-packages/torch/nn/modules/module.py", line 550, in __call__
    result = self.forward(*input, **kwargs)
  File "train.py", line 76, in forward
    _, regression, classification, anchors = self.model(imgs)
  File "/usr/local/lib/python3.6/dist-packages/torch/nn/modules/module.py", line 550, in __call__
    result = self.forward(*input, **kwargs)
  File "/content/EfficientDetwithSavedWeights/backbone.py", line 65, in forward
    _, p3, p4, p5 = self.backbone_net(inputs)
  File "/usr/local/lib/python3.6/dist-packages/torch/nn/modules/module.py", line 550, in __call__
    result = self.forward(*input, **kwargs)
  File "/content/EfficientDetwithSavedWeights/efficientdet/model.py", line 412, in forward
    x = block(x, drop_connect_rate=drop_connect_rate)
  File "/usr/local/lib/python3.6/dist-packages/torch/nn/modules/module.py", line 550, in __call__
    result = self.forward(*input, **kwargs)
  File "/content/EfficientDetwithSavedWeights/efficientnet/model.py", line 78, in forward
    x = self._bn0(x)
  File "/usr/local/lib/python3.6/dist-packages/torch/nn/modules/module.py", line 550, in __call__
    result = self.forward(*input, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/torch/nn/modules/batchnorm.py", line 106, in forward
    exponential_average_factor, self.eps)
  File "/usr/local/lib/python3.6/dist-packages/torch/nn/functional.py", line 1923, in batch_norm
    training, momentum, eps, torch.backends.cudnn.enabled
RuntimeError: CUDA out of memory. Tried to allocate 450.00 MiB (GPU 0; 11.17 GiB total capacity; 10.17 GiB already allocated; 415.75 MiB free; 10.46 GiB reserved in total by PyTorch)
`

**Comment by zylo117** [comment]
reduce batchsize or train with a smaller network like d0.

**Comment by singlautsav** [comment]
but I have been working with d1 for a long time now.. I had iterations upto 31500, why did this suddenly start failing?

**Comment by zylo117** [comment]
you need to check your gpu using nvidia-smi. sometimes google will give you another type of gpu.
It could be K80 16G, sometimes P4 8G.
