### ISSUE TITLE
Merge introduced problems in utils_extra

### ISSUE THREAD

**Issue by mnslarcher** [zylo117/Yet-Another-EfficientDet-Pytorch#278]
Hi @zylo117, your merge introduced problems:

```
<<<<<<< HEAD
<<<<<<< HEAD
        extra_h = (w - 1) * self.stride[1] - w + self.kernel_size[1]
        extra_v = (h - 1) * self.stride[0] - h + self.kernel_size[0]
=======
        extra_h = (math.ceil(w / self.stride[1]) - 1) * self.stride[1] - w + self.kernel_size[1]
        extra_v = (math.ceil(h / self.stride[0]) - 1) * self.stride[0] - h + self.kernel_size[0]

        extra_h = h_cover_len - w
        extra_v = v_cover_len - h
>>>>>>> 21771ddb20591a2ff85cb2227f586e63f72c94f8
=======
        extra_h = (math.ceil(w / self.stride[1]) - 1) * self.stride[1] - w + self.kernel_size[1]
        extra_v = (math.ceil(h / self.stride[0]) - 1) * self.stride[0] - h + self.kernel_size[0]
>>>>>>> dc738a48daad9cc3530dd1beee5f4235b363687a
```

https://github.com/zylo117/Yet-Another-EfficientDet-Pytorch/blob/master/efficientnet/utils_extra.py

**Comment by samiullah225** [comment]
removing those <<<<HEAD and extra =====  causes,


Traceback (most recent call last):
  File "train.py", line 325, in <module>
    train(opt)
  File "train.py", line 276, in train
    cls_loss, reg_loss = model(imgs, annot, obj_list=params.obj_list)
  File "/usr/local/lib/python3.6/dist-packages/torch/nn/modules/module.py", line 532, in __call__
    result = self.forward(*input, **kwargs)
  File "train.py", line 74, in forward
    _, regression, classification, anchors = self.model(imgs)
  File "/usr/local/lib/python3.6/dist-packages/torch/nn/modules/module.py", line 532, in __call__
    result = self.forward(*input, **kwargs)
  File "/content/Yet-Another-EfficientDet-Pytorch/backbone.py", line 65, in forward
    _, p3, p4, p5 = self.backbone_net(inputs)
  File "/usr/local/lib/python3.6/dist-packages/torch/nn/modules/module.py", line 532, in __call__
    result = self.forward(*input, **kwargs)
  File "/content/Yet-Another-EfficientDet-Pytorch/efficientdet/model.py", line 399, in forward
    x = self.model._conv_stem(x)
  File "/usr/local/lib/python3.6/dist-packages/torch/nn/modules/module.py", line 532, in __call__
    result = self.forward(*input, **kwargs)
  File "/content/Yet-Another-EfficientDet-Pytorch/efficientnet/utils_extra.py", line 44, in forward
    extra_h = h_cover_len - w
NameError: name 'h_cover_len' is not defined

**Comment by zylo117** [comment]
sorry for the troubles, fixed
