### ISSUE TITLE
RuntimeError: CUDA out of memory got this error

### ISSUE THREAD

**Issue by samiullah225** [zylo117/Yet-Another-EfficientDet-Pytorch#279]
/usr/local/lib/python3.6/dist-packages/numpy/core/fromnumeric.py:3118: RuntimeWarning: Mean of empty slice.
  out=out, **kwargs)
/usr/local/lib/python3.6/dist-packages/numpy/core/_methods.py:85: RuntimeWarning: invalid value encountered in double_scalars
  ret = ret.dtype.type(ret / rcount)
Traceback (most recent call last):
  File "train.py", line 325, in <module>
    train(opt)
  File "train.py", line 276, in train
    cls_loss, reg_loss = model(imgs, annot, obj_list=params.obj_list)
  File "/usr/local/lib/python3.6/dist-packages/torch/nn/modules/module.py", line 532, in __call__
    result = self.forward(*input, **kwargs)
  File "train.py", line 74, in forward
    _, regression, classification, anchors = self.model(imgs)
  File "/usr/local/lib/python3.6/dist-packages/torch/nn/modules/module.py", line 532, in __call__
    result = self.forward(*input, **kwargs)
  File "/content/Yet-Another-EfficientDet-Pytorch/backbone.py", line 65, in forward
    _, p3, p4, p5 = self.backbone_net(inputs)
  File "/usr/local/lib/python3.6/dist-packages/torch/nn/modules/module.py", line 532, in __call__
    result = self.forward(*input, **kwargs)
  File "/content/Yet-Another-EfficientDet-Pytorch/efficientdet/model.py", line 412, in forward
    x = block(x, drop_connect_rate=drop_connect_rate)
  File "/usr/local/lib/python3.6/dist-packages/torch/nn/modules/module.py", line 532, in __call__
    result = self.forward(*input, **kwargs)
  File "/content/Yet-Another-EfficientDet-Pytorch/efficientnet/model.py", line 78, in forward
    x = self._bn0(x)
  File "/usr/local/lib/python3.6/dist-packages/torch/nn/modules/module.py", line 532, in __call__
    result = self.forward(*input, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/torch/nn/modules/batchnorm.py", line 107, in forward
    exponential_average_factor, self.eps)
  File "/usr/local/lib/python3.6/dist-packages/torch/nn/functional.py", line 1670, in batch_norm
    training, momentum, eps, torch.backends.cudnn.enabled
RuntimeError: CUDA out of memory. Tried to allocate 3.00 GiB (GPU 0; 7.43 GiB total capacity; 3.61 GiB already allocated; 800.94 MiB free; 6.13 GiB reserved in total by PyTorch)

**Comment by zylo117** [comment]
reduce batchsize or use smaller network
