### ISSUE TITLE
Tried running efficientdet_test.py it gave this error  The size of tensor a (512) must match the size of tensor b (1024) at non-singleton dimension 3

### ISSUE THREAD

**Issue by samiullah225** [zylo117/Yet-Another-EfficientDet-Pytorch#281]
Traceback (most recent call last):
  File "efficientdet_test.py", line 71, in <module>
    features, regression, classification, anchors = model(x)
  File "/usr/local/lib/python3.6/dist-packages/torch/nn/modules/module.py", line 532, in __call__
    result = self.forward(*input, **kwargs)
  File "/content/Yet-Another-EfficientDet-Pytorch/backbone.py", line 68, in forward
    features = self.bifpn(features)
  File "/usr/local/lib/python3.6/dist-packages/torch/nn/modules/module.py", line 532, in __call__
    result = self.forward(*input, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/torch/nn/modules/container.py", line 100, in forward
    input = module(input)
  File "/usr/local/lib/python3.6/dist-packages/torch/nn/modules/module.py", line 532, in __call__
    result = self.forward(*input, **kwargs)
  File "/content/Yet-Another-EfficientDet-Pytorch/efficientdet/model.py", line 175, in forward
    p3_out, p4_out, p5_out, p6_out, p7_out = self._forward_fast_attention(inputs)
  File "/content/Yet-Another-EfficientDet-Pytorch/efficientdet/model.py", line 202, in _forward_fast_attention
    p6_up = self.conv6_up(self.swish(weight[0] * p6_in + weight[1] * self.p6_upsample(p7_in)))
RuntimeError: The size of tensor a (512) must match the size of tensor b (1024) at non-singleton dimension 3

**Comment by workingcoder** [comment]
Have you solved the problem？I have the same problem when I'm running coco_eval.py.

**Comment by samiullah225** [comment]
> Have you solved the problem？I have the same problem when I'm running coco_eval.py.

No. waiting for author's help

**Comment by zylo117** [comment]
please provide the minimum code to replicate

**Comment by batuhanfaik** [comment]
> please provide the minimum code to replicate

`python coco_eval.py -c 0` does the trick

**Comment by zylo117** [comment]
bug, fixed

**Comment by alsheabi** [comment]
@zylo117 I faced the same error. How did solve this issue?

**Comment by zylo117** [comment]
@alsheabi I don't think this is the same error as yours. Because this bug had been fixed a long ago
