### ISSUE TITLE
utility_extra mod. create a CUDA oom problem?

### ISSUE THREAD

**Issue by mnslarcher** [zylo117/Yet-Another-EfficientDet-Pytorch#284]
I'm training efficient-det0 with an AWS instance ml.p3.16xlarge, before I was able to do it but now I get this error, is possible that is related to the last modification of utility_extra?:

UPDATE: I tried again starting from another checkpoint and it works so is probably something introduced with the last modification of the code

```
Traceback (most recent call last):
  File "train.py", line 725, in <module>
    train(args)
  File "train.py", line 669, in train
    cls_loss, reg_loss = model(imgs, annotations)
  File "/opt/conda/lib/python3.6/site-packages/torch/nn/modules/module.py", line 543, in __call__
    result = self.forward(*input, **kwargs)
  File "/opt/conda/lib/python3.6/site-packages/torch/nn/parallel/data_parallel.py", line 152, in forward
    outputs = self.parallel_apply(replicas, inputs, kwargs)
  File "/opt/conda/lib/python3.6/site-packages/torch/nn/parallel/data_parallel.py", line 162, in parallel_apply
    return parallel_apply(replicas, inputs, kwargs, self.device_ids[:len(replicas)])
  File "/opt/conda/lib/python3.6/site-packages/torch/nn/parallel/parallel_apply.py", line 85, in parallel_apply
    output.reraise()
  File "/opt/conda/lib/python3.6/site-packages/torch/_utils.py", line 394, in reraise
    raise self.exc_type(msg)
RuntimeError: Caught RuntimeError in replica 0 on device 0.
Original Traceback (most recent call last):
  File "/opt/conda/lib/python3.6/site-packages/torch/nn/parallel/parallel_apply.py", line 60, in _worker
    output = module(*input, **kwargs)
  File "/opt/conda/lib/python3.6/site-packages/torch/nn/modules/module.py", line 543, in __call__
    result = self.forward(*input, **kwargs)
  File "train.py", line 341, in forward
    _, regressions, classifications, anchors = self.model(imgs)
  File "/opt/conda/lib/python3.6/site-packages/torch/nn/modules/module.py", line 543, in __call__
    result = self.forward(*input, **kwargs)
  File "/opt/ml/code/backbone.py", line 65, in forward
    _, p3, p4, p5 = self.backbone_net(inputs)
  File "/opt/conda/lib/python3.6/site-packages/torch/nn/modules/module.py", line 543, in __call__
    result = self.forward(*input, **kwargs)
  File "/opt/ml/code/efficientdet/model.py", line 412, in forward
    x = block(x, drop_connect_rate=drop_connect_rate)
  File "/opt/conda/lib/python3.6/site-packages/torch/nn/modules/module.py", line 543, in __call__
    result = self.forward(*input, **kwargs)
  File "/opt/ml/code/efficientnet/model.py", line 81, in forward
    x = self._depthwise_conv(x)
  File "/opt/conda/lib/python3.6/site-packages/torch/nn/modules/module.py", line 543, in __call__
    result = self.forward(*input, **kwargs)
  File "/opt/ml/code/efficientnet/utils_extra.py", line 44, in forward
    x = F.pad(x, [left, right, top, bottom])
  File "/opt/conda/lib/python3.6/site-packages/torch/nn/functional.py", line 2862, in pad
    return _VF.constant_pad_nd(input, pad, value)
RuntimeError: CUDA out of memory. Tried to allocate 10.56 GiB (GPU 0; 15.78 GiB total capacity; 3.40 GiB already allocated; 9.89 GiB free; 4.83 GiB reserved in total by PyTorch)

2020-05-10 12:58:17 Uploading - Uploading generated training model
2020-05-10 12:58:17 Failed - Training job failed
```

**Comment by zylo117** [comment]
i think it's batched nms instead of conv padding

**Comment by zylo117** [comment]
https://github.com/zylo117/Yet-Another-EfficientDet-Pytorch/commit/bbceb2e31df956577d7303785259ca7d73e6cda9 fixed.
