### ISSUE TITLE
Tried running train.py it gave this error The size of tensor a (28) must match the size of tensor b (56) at non-singleton dimension 3

### ISSUE THREAD

**Issue by kuangsangudu** [zylo117/Yet-Another-EfficientDet-Pytorch#286]
Traceback (most recent call last):
  File "train.py", line 325, in <module>
    train(opt)
  File "train.py", line 276, in train
    cls_loss, reg_loss = model(imgs, annot, obj_list=params.obj_list)
  File "D:\conda\lib\site-packages\torch\nn\modules\module.py", line 550, in __call__
    result = self.forward(*input, **kwargs)
  File "train.py", line 74, in forward
    _, regression, classification, anchors = self.model(imgs)
  File "D:\conda\lib\site-packages\torch\nn\modules\module.py", line 550, in __call__
    result = self.forward(*input, **kwargs)
  File "D:\the last paper\code\EfficientDet\Yet-Another-EfficientDet-Pytorch-master(1)\Yet-Another-EfficientDet-Pytorch-master\backbone.py", line 68, in forward
    features = self.bifpn(features)
  File "D:\conda\lib\site-packages\torch\nn\modules\module.py", line 550, in __call__
    result = self.forward(*input, **kwargs)
  File "D:\conda\lib\site-packages\torch\nn\modules\container.py", line 100, in forward
    input = module(input)
  File "D:\conda\lib\site-packages\torch\nn\modules\module.py", line 550, in __call__
    result = self.forward(*input, **kwargs)
  File "D:\the last paper\code\EfficientDet\Yet-Another-EfficientDet-Pytorch-master(1)\Yet-Another-EfficientDet-Pytorch-master\efficientdet\model.py", line 175, in forward
    p3_out, p4_out, p5_out, p6_out, p7_out = self._forward_fast_attention(inputs)
  File "D:\the last paper\code\EfficientDet\Yet-Another-EfficientDet-Pytorch-master(1)\Yet-Another-EfficientDet-Pytorch-master\efficientdet\model.py", line 202, in _forward_fast_attention
    p6_up = self.conv6_up(self.swish(weight[0] * p6_in + weight[1] * self.p6_upsample(p7_in)))
RuntimeError: The size of tensor a (28) must match the size of tensor b (56) at non-singleton dimension 3

**Comment by zylo117** [comment]
did you update the latest code

**Comment by kuangsangudu** [comment]
sorry,  i did't update the latest code. I can run the code now.
