### ISSUE TITLE
模型尺寸必须是128的倍数吗？

### ISSUE THREAD

**Issue by zhouzhubin** [zylo117/Yet-Another-EfficientDet-Pytorch#307]
@zylo117 大佬您好，模型尺寸必须得是128的倍数吗？我试了608的尺寸，用的是d0的模型，会报如下错误：
Traceback (most recent call last):
  File "efficientdet_test.py", line 71, in <module>
    features, regression, classification, anchors = model(x)
  File "/usr/local/lib/python3.6/dist-packages/torch/nn/modules/module.py", line 532, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/zhouzhubin/workspace/project/pytorch/test_efficientdet/Yet-Another-EfficientDet-Pytorch/backbone.py", line 68, in forward
    features = self.bifpn(features)
  File "/usr/local/lib/python3.6/dist-packages/torch/nn/modules/module.py", line 532, in __call__
    result = self.forward(*input, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/torch/nn/modules/container.py", line 100, in forward
    input = module(input)
  File "/usr/local/lib/python3.6/dist-packages/torch/nn/modules/module.py", line 532, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/zhouzhubin/workspace/project/pytorch/test_efficientdet/Yet-Another-EfficientDet-Pytorch/efficientdet/model.py", line 175, in forward
    p3_out, p4_out, p5_out, p6_out, p7_out = self._forward_fast_attention(inputs)
  File "/home/zhouzhubin/workspace/project/pytorch/test_efficientdet/Yet-Another-EfficientDet-Pytorch/efficientdet/model.py", line 208, in _forward_fast_attention
    p5_up = self.conv5_up(self.swish(weight[0] * p5_in + weight[1] * self.p5_upsample(p6_up)))
RuntimeError: The size of tensor a (19) must match the size of tensor b (20) at non-singleton dimension 3
也试过原版tensorflow的608尺寸，那个是可以运行的。

**Comment by zylo117** [comment]
The official repo will pad the image accordingly. This repo doesn't

**Comment by zhouzhubin** [comment]
@zylo117 哦哦，好吧，谢谢您了啊！

**Comment by zhouzhubin** [comment]
@zylo117 您好，如果我想在您的工程里加入多尺度训练的话，图片的输入尺寸就必须是128的倍数或者说pading成128的倍数了

**Comment by zylo117** [comment]
yes

**Comment by zhouzhubin** [comment]
恩恩，好的，谢谢了

**Comment by zylo117** [comment]
problem solved, closed.
