### ISSUE TITLE
KeyError when eval

### ISSUE THREAD

**Issue by czzbb** [zylo117/Yet-Another-EfficientDet-Pytorch#311]
When I ran the eval_coco.py, this happened
````
Traceback (most recent call last):
  File "coco_eval.py", line 168, in <module>
    _eval(coco_gt, image_ids, f'{SET_NAME}_bbox_results.json')
  File "coco_eval.py", line 140, in _eval
    coco_eval.evaluate()
  File "/home/zzb/anaconda3/envs/torch1.4/lib/python3.6/site-packages/pycocotools/cocoeval.py", line 156, in evaluate
    for catId in catIds
  File "/home/zzb/anaconda3/envs/torch1.4/lib/python3.6/site-packages/pycocotools/cocoeval.py", line 158, in <listcomp>
    for imgId in p.imgIds
  File "/home/zzb/anaconda3/envs/torch1.4/lib/python3.6/site-packages/pycocotools/cocoeval.py", line 252, in evaluateImg
    if g['ignore'] or (g['area']<aRng[0] or g['area']>aRng[1]):
KeyError:'area'
```
btw, which version of python do you use for this project?

**Comment by JackeyGuo** [comment]
Hi, can you solve your problem? i met the same problem.

**Comment by czzbb** [comment]
Sorry to reply to you so late. The error results from your json files. Your annotations should contain key 'area'.



------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Arthur"<notifications@github.com&gt;; 
发送时间: 2020年5月24日(星期天) 晚上9:32
收件人: "zylo117/Yet-Another-EfficientDet-Pytorch"<Yet-Another-EfficientDet-Pytorch@noreply.github.com&gt;; 
抄送: "zzb"<1024179279@qq.com&gt;; "State change"<state_change@noreply.github.com&gt;; 
主题: Re: [zylo117/Yet-Another-EfficientDet-Pytorch] KeyError when eval (#311)





 
Hi, can you solve your problem? i met the same problem.
