### ISSUE TITLE
Got cuda out of memory on my RTX 2080ti when running efficientdet_test.py???

### ISSUE THREAD

**Issue by xiong-peng** [zylo117/Yet-Another-EfficientDet-Pytorch#32]
(py3.6.2) @hpcl-X299-UD4-Pro:~/peng/code/Yet-Another-EfficientDet-Pytorch$ python efficientdet_test.py
running speed test...
test1: model inferring and postprocessing
inferring image for 10 times...
0.07670512199401855 seconds, 13.036939046625593 FPS, @batch_size 1
test2: model inferring only
inferring images for batch_size 32 for 10 times...
Traceback (most recent call last):
  File "efficientdet_test.py", line 127, in <module>
    _, regression, classification, anchors = model(x)
  File "/home/.pyenv/versions/py3.6.2/lib/python3.6/site-packages/torch/nn/modules/module.py", line 532, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/peng/code/Yet-Another-EfficientDet-Pytorch/backbone.py", line 73, in forward
    _, p3, p4, p5 = self.backbone_net(inputs)
  File "/home/.pyenv/versions/py3.6.2/lib/python3.6/site-packages/torch/nn/modules/module.py", line 532, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/peng/code/Yet-Another-EfficientDet-Pytorch/efficientdet/model.py", line 401, in forward
    x = self.model._swish(x)
  File "/home/.pyenv/versions/py3.6.2/lib/python3.6/site-packages/torch/nn/modules/module.py", line 532, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/peng/code/Yet-Another-EfficientDet-Pytorch/efficientnet/utils.py", line 54, in forward
    return SwishImplementation.apply(x)
  File "/home/peng/code/Yet-Another-EfficientDet-Pytorch/efficientnet/utils.py", line 41, in forward
    result = i * torch.sigmoid(i)
RuntimeError: CUDA out of memory. Tried to allocate 3.52 GiB (GPU 0; 10.76 GiB total capacity; 8.64 GiB already allocated; 863.62 MiB free; 8.91 GiB reserved in total by PyTorch)

**Comment by zylo117** [comment]
It's normal, because test2 is extreme fps test with batchsize 32. I should have comment it by default

**Comment by xiong-peng** [comment]
Alright
