### ISSUE TITLE
eval after 17 epochs: the model does not provide any valid output

### ISSUE THREAD

**Issue by williamscott701** [zylo117/Yet-Another-EfficientDet-Pytorch#346]
python coco_eval.py -p coco -c 3 -w logs/coco2017/efficientdet-d3_17_70000.pth --float16 True
running coco-style evaluation on project coco, weights logs/coco2017/efficientdet-d3_17_70000.pth...
loading annotations into memory...
Done (t=0.01s)
creating index...
index created!
100%|████████████████████████████████████████████████████████████████████████████████████| 990/990 [03:08<00:00,  4.96it/s]
Traceback (most recent call last):
  File "coco_eval.py", line 164, in <module>
    image_ids = evaluate_coco(VAL_IMGS, SET_NAME, image_ids, coco_gt, model)
  File "coco_eval.py", line 119, in evaluate_coco
    raise Exception('the model does not provide any valid output, check model architecture and the data input')
Exception: the model does not provide any valid output, check model architecture and the data input

**Comment by zylo117** [comment]
if you are not training with f16, don't use f16

**Comment by williamscott701** [comment]
Hi Zylo117, Thank you for being so active.

if i remove the f16's the following is what i get:

python coco_eval.py -p coco -c 3 -w logs/coco2017/efficientdet-d3_17_67500.pth
running coco-style evaluation on project coco, weights logs/coco2017/efficientdet-d3_17_67500.pth...
loading annotations into memory...
Done (t=0.01s)
creating index...
index created!
100%|████████████████████████████████████████████████████████████████████████████████████| 990/990 [03:04<00:00,  5.25it/s]
Traceback (most recent call last):
  File "coco_eval.py", line 163, in <module>
    image_ids = evaluate_coco(VAL_IMGS, SET_NAME, image_ids, coco_gt, model)
  File "coco_eval.py", line 118, in evaluate_coco
    raise Exception('the model does not provide any valid output, check model architecture and the data input')
Exception: the model does not provide any valid output, check model architecture and the data input

**Comment by zylo117** [comment]
well then it meant what it said. the model does not provide any valid output, check model architecture and the data input

**Comment by hktxt** [comment]
seems like Im not the only one who encount the same problem.
I trianed model on my own dataset for a day, the loss dicreased normly
after 20 epoch, I tried to inference the model I trained on test image and draw bbox. 
not even single object was detected correctly...

**Comment by zylo117** [comment]
@hktxt please refer to the FAQs
https://github.com/zylo117/Yet-Another-EfficientDet-Pytorch/issues/386

**Comment by wgqbit95** [comment]
Have you solved this problem?  I have encountered the problem too. o(╥﹏╥)o @hktxt

**Comment by hktxt** [comment]
@wgqbit95  nope.
I perfer another implementation: [rwightman-efficientdet-pytorch](https://github.com/rwightman/efficientdet-pytorch ), which converged in 30 epochs on my dataset.

**Comment by wgqbit95** [comment]
> @wgqbit95 nope.
> I perfer another implementation: [rwightman-efficientdet-pytorch](https://github.com/rwightman/efficientdet-pytorch), which converged in 30 epochs on my dataset.

Thank you for sharing! And perhaps I have found where the problem is. First, I use the AdamW optimization method instead of SGD (I met this problem when i use SGD). Second, I use this repo https://github.com/ChangeZH/ALL2COCO to regenerate the coco format json file and the AP is not -1 now. Hope this can help you~

**Comment by mDp0r** [comment]
I'm having this problem as well. Any suggestions on what to check exactly regarding architecture and input? Or any tests I can do to enclose the problem?
