### ISSUE TITLE
RuntimeError: non-empty 3D or 4D input tensor expected but got ndim: 4  When run training efficientdet-d7

### ISSUE THREAD

**Issue by hongrui16** [zylo117/Yet-Another-EfficientDet-Pytorch#348]
**RuntimeError: cannot reshape tensor of 0 elements into shape [0, 56, -1] because the unspecified dimension size -1 can be any value and is ambiguous**

100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1855/1855 [15:38<00:00,  1.98it/s]
/root/anaconda2/envs/tf_2_pytorch_1_5/lib/python3.6/site-packages/numpy/core/fromnumeric.py:3335: RuntimeWarning: Mean of empty slice.
  out=out, **kwargs)
/root/anaconda2/envs/tf_2_pytorch_1_5/lib/python3.6/site-packages/numpy/core/_methods.py:161: RuntimeWarning: invalid value encountered in double_scalars
  ret = ret.dtype.type(ret / rcount)
Traceback (most recent call last):
  File "train.py", line 378, in <module>
    train(opt)
  File "train.py", line 328, in train
    cls_loss, reg_loss = model(imgs, annot, obj_list=params.obj_list)
  File "/root/anaconda2/envs/tf_2_pytorch_1_5/lib/python3.6/site-packages/torch/nn/modules/module.py", line 550, in __call__
    result = self.forward(*input, **kwargs)
  File "/root/anaconda2/envs/tf_2_pytorch_1_5/lib/python3.6/site-packages/torch/nn/parallel/data_parallel.py", line 155, in forward
    outputs = self.parallel_apply(replicas, inputs, kwargs)
  File "/root/anaconda2/envs/tf_2_pytorch_1_5/lib/python3.6/site-packages/torch/nn/parallel/data_parallel.py", line 165, in parallel_apply
    return parallel_apply(replicas, inputs, kwargs, self.device_ids[:len(replicas)])
  File "/root/anaconda2/envs/tf_2_pytorch_1_5/lib/python3.6/site-packages/torch/nn/parallel/parallel_apply.py", line 85, in parallel_apply
    output.reraise()
  File "/root/anaconda2/envs/tf_2_pytorch_1_5/lib/python3.6/site-packages/torch/_utils.py", line 395, in reraise
    raise self.exc_type(msg)
RuntimeError: Caught RuntimeError in replica 0 on device 0.
Original Traceback (most recent call last):
  File "/root/anaconda2/envs/tf_2_pytorch_1_5/lib/python3.6/site-packages/torch/nn/parallel/parallel_apply.py", line 60, in _worker
    output = module(*input, **kwargs)
  File "/root/anaconda2/envs/tf_2_pytorch_1_5/lib/python3.6/site-packages/torch/nn/modules/module.py", line 550, in __call__
    result = self.forward(*input, **kwargs)
  File "train.py", line 88, in forward
    _, regression, classification, anchors = self.model(imgs)
  File "/root/anaconda2/envs/tf_2_pytorch_1_5/lib/python3.6/site-packages/torch/nn/modules/module.py", line 550, in __call__
    result = self.forward(*input, **kwargs)
  File "/workspace/..../efficientdet/Yet-Another-EfficientDet-Pytorch/backbone.py", line 68, in forward
    features = self.bifpn(features)
  File "/root/anaconda2/envs/tf_2_pytorch_1_5/lib/python3.6/site-packages/torch/nn/modules/module.py", line 550, in __call__
    result = self.forward(*input, **kwargs)
  File "/root/anaconda2/envs/tf_2_pytorch_1_5/lib/python3.6/site-packages/torch/nn/modules/container.py", line 100, in forward
    input = module(input)
  File "/root/anaconda2/envs/tf_2_pytorch_1_5/lib/python3.6/site-packages/torch/nn/modules/module.py", line 550, in __call__
    result = self.forward(*input, **kwargs)
  File "/workspace/..../efficientdet/Yet-Another-EfficientDet-Pytorch/efficientdet/model.py", line 177, in forward
    p3_out, p4_out, p5_out, p6_out, p7_out = self._forward(inputs)
  File "/workspace/..../efficientdet/Yet-Another-EfficientDet-Pytorch/efficientdet/model.py", line 259, in _forward
    p6_in = self.p5_to_p6(p5)
  File "/root/anaconda2/envs/tf_2_pytorch_1_5/lib/python3.6/site-packages/torch/nn/modules/module.py", line 550, in __call__
    result = self.forward(*input, **kwargs)
  File "/root/anaconda2/envs/tf_2_pytorch_1_5/lib/python3.6/site-packages/torch/nn/modules/container.py", line 100, in forward
    input = module(input)
  File "/root/anaconda2/envs/tf_2_pytorch_1_5/lib/python3.6/site-packages/torch/nn/modules/module.py", line 550, in __call__
    result = self.forward(*input, **kwargs)
  File "/workspace/15_raid/..../...../efficientdet/Yet-Another-EfficientDet-Pytorch/efficientnet/utils_extra.py", line 85, in forward
    x = self.pool(x)
  File "/root/anaconda2/envs/tf_2_pytorch_1_5/lib/python3.6/site-packages/torch/nn/modules/module.py", line 550, in __call__
    result = self.forward(*input, **kwargs)
  File "/root/anaconda2/envs/tf_2_pytorch_1_5/lib/python3.6/site-packages/torch/nn/modules/pooling.py", line 141, in forward
    self.return_indices)
  File "/root/anaconda2/envs/tf_2_pytorch_1_5/lib/python3.6/site-packages/torch/_jit_internal.py", line 209, in fn
    return if_false(*args, **kwargs)
  File "/root/anaconda2/envs/tf_2_pytorch_1_5/lib/python3.6/site-packages/torch/nn/functional.py", line 539, in _max_pool2d
    input, kernel_size, stride, padding, dilation, ceil_mode)
**RuntimeError: non-empty 3D or 4D input tensor expected but got ndim: 4**

any useful solution?

**Comment by hongrui16** [comment]
@zylo117 
have you ever come across the problem？
thanks

**Comment by zylo117** [comment]
I haven't. You should post your minimal code here so that others can replicate your issue.
