### ISSUE TITLE
TypeError: unsupported operand type(s) for /: 'NoneType' and 'int'

### ISSUE THREAD

**Issue by dapsjj** [zylo117/Yet-Another-EfficientDet-Pytorch#350]
When I run `efficientdet_test.py`,the error message is :
```
Traceback (most recent call last):
  File "E:/test/Yet-Another-EfficientDet-Pytorch-master/efficientdet_test.py", line 50, in <module>
    ori_imgs, framed_imgs, framed_metas = preprocess(img_path, max_size=input_size)
  File "E:\test\Yet-Another-EfficientDet-Pytorch-master\utils\utils.py", line 71, in preprocess
    normalized_imgs = [(img / 255 - mean) / std for img in ori_imgs]
  File "E:\test\Yet-Another-EfficientDet-Pytorch-master\utils\utils.py", line 71, in <listcomp>
    normalized_imgs = [(img / 255 - mean) / std for img in ori_imgs]
TypeError: unsupported operand type(s) for /: 'NoneType' and 'int'

```
How to fix it

**Comment by dapsjj** [comment]
When I use `img_path = r'E:/test/Yet-Another-EfficientDet-Pytorch-master/test/img.png'` in `efficientdet_test.py`
The error disappeared.
