### ISSUE TITLE
KeyError: 'p' when I train custom dataset

### ISSUE THREAD

**Issue by dapsjj** [zylo117/Yet-Another-EfficientDet-Pytorch#351]
The images in val folder likes this:
```
--datasets
   --garbage
       --val
          --cardboard_1.jpg
          --cardboard_2.jpg
          --cardboard_3.jpg
          ……
          --cardboard_99999.jpg
          --bottle_1.jpg
          ……
          --bottle_99999.jpg
      --train
          --orange_1.jpg
          --orange_2.jpg
          --orange_3.jpg
          ……
          --orange_99999.jpg
          --plastic_1.jpg
          ……
          --plastic_99999.jpg
```
When I run `train.py`,the error message is:
### 

0%|          | 0/813 [00:00<?, ?it/s]Traceback (most recent call last):
  File "E:/test/Yet-Another-EfficientDet-Pytorch-master/train.py", line 331, in <module>
    train(opt)
  File "E:/test/Yet-Another-EfficientDet-Pytorch-master/train.py", line 216, in train
    for iter, data in enumerate(progress_bar):
  File "C:\Users\pe\Anaconda3\lib\site-packages\tqdm\std.py", line 1081, in __iter__
    for obj in iterable:
  File "C:\Users\pe\Anaconda3\lib\site-packages\torch\utils\data\dataloader.py", line 345, in __next__
    data = self._next_data()
  File "C:\Users\pe\Anaconda3\lib\site-packages\torch\utils\data\dataloader.py", line 856, in _next_data
    return self._process_data(data)
  File "C:\Users\pe\Anaconda3\lib\site-packages\torch\utils\data\dataloader.py", line 881, in _process_data
    data.reraise()
  File "C:\Users\pe\Anaconda3\lib\site-packages\torch\_utils.py", line 395, in reraise
    raise self.exc_type(msg)
KeyError: Caught KeyError in DataLoader worker process 0.
Original Traceback (most recent call last):
  File "C:\Users\pe\Anaconda3\lib\site-packages\torch\utils\data\_utils\worker.py", line 178, in _worker_loop
    data = fetcher.fetch(index)
  File "C:\Users\pe\Anaconda3\lib\site-packages\torch\utils\data\_utils\fetch.py", line 44, in fetch
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "C:\Users\pe\Anaconda3\lib\site-packages\torch\utils\data\_utils\fetch.py", line 44, in <listcomp>
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "E:\test\Yet-Another-EfficientDet-Pytorch-master\efficientdet\dataset.py", line 43, in __getitem__
    img = self.load_image(idx)
  File "E:\test\Yet-Another-EfficientDet-Pytorch-master\efficientdet\dataset.py", line 51, in load_image
    image_info = self.coco.loadImgs(self.image_ids[image_index])[0]
  File "C:\Users\pe\Anaconda3\lib\site-packages\pycocotools\coco.py", line 230, in loadImgs
    return [self.imgs[id] for id in ids]
  File "C:\Users\pe\Anaconda3\lib\site-packages\pycocotools\coco.py", line 230, in <listcomp>
    return [self.imgs[id] for id in ids]
KeyError: 'p'

  0%|          | 0/813 [00:15<?, ?it/s]

Where is wrong,how to fix it?

**Comment by zylo117** [comment]
check image_ids, image_ids should be int, not str
some annotation convertion may use str but it's not standard

**Comment by dapsjj** [comment]
@zylo117 Very helpful,thanks!
