### ISSUE TITLE
Cuda Out of memory issue

### ISSUE THREAD

**Issue by frank-qcd-qk** [zylo117/Yet-Another-EfficientDet-Pytorch#378]
Hi, 
During training, I constantly got error telling me CUDA out of memory, is there any steps I can take to prevent it?

> CUDA out of memory. Tried to allocate 7.88 GiB (GPU 0; 7.93 GiB total capacity; 3.57 GiB already allocated; 3.26 GiB free; 3.60 GiB reserved in total by PyTorch)
  9%|█████████████████                                                                                                                                                                                | 11/124 [01:19<06:46,  3.59s/it][Error] Traceback (most recent call last):
  File "efficientDetCore/train.py", line 231, in train
    cls_loss, reg_loss = model(imgs, annot, obj_list=params.obj_list)
  File "/home/frank/.local/lib/python3.6/site-packages/torch/nn/modules/module.py", line 532, in __call__
    result = self.forward(*input, **kwargs)
  File "efficientDetCore/train.py", line 80, in forward
    _, regression, classification, anchors = self.model(imgs)
  File "/home/frank/.local/lib/python3.6/site-packages/torch/nn/modules/module.py", line 532, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/frank/objectCXR/object-cxr-2020-EfficientDet_trainer/efficientDetCore/backbone.py", line 65, in forward
    _, p3, p4, p5 = self.backbone_net(inputs)
  File "/home/frank/.local/lib/python3.6/site-packages/torch/nn/modules/module.py", line 532, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/frank/objectCXR/object-cxr-2020-EfficientDet_trainer/efficientDetCore/efficientdet/model.py", line 399, in forward
    x = self.model._conv_stem(x)
  File "/home/frank/.local/lib/python3.6/site-packages/torch/nn/modules/module.py", line 532, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/frank/objectCXR/object-cxr-2020-EfficientDet_trainer/efficientDetCore/efficientnet/utils_extra.py", line 46, in forward
    x = self.conv(x)
  File "/home/frank/.local/lib/python3.6/site-packages/torch/nn/modules/module.py", line 532, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/frank/.local/lib/python3.6/site-packages/torch/nn/modules/conv.py", line 345, in forward
    return self.conv2d_forward(input, self.weight)
  File "/home/frank/.local/lib/python3.6/site-packages/torch/nn/modules/conv.py", line 342, in conv2d_forward
    self.padding, self.dilation, self.groups)
RuntimeError: CUDA out of memory. Tried to allocate 7.88 GiB (GPU 0; 7.93 GiB total capacity; 3.57 GiB already allocated; 3.26 GiB free; 3.60 GiB reserved in total by PyTorch)

CUDA out of memory. Tried to allocate 7.88 GiB (GPU 0; 7.93 GiB total capacity; 3.57 GiB already allocated; 3.26 GiB free; 3.60 GiB reserved in total by PyTorch)

**Comment by frank-qcd-qk** [comment]
OK, this seems that d7 just is resource hungry. need better gpu... sigh...

**Comment by dimimal** [comment]
Hi, 
I got the same issue. When trying to train D7x end to end on a V100 with 16GB of memory, I get the same error. Even with single sample per gpu. I also, tried to use 1 worker but it didnt work either. Has anyone trained this model end-to-end?

**Comment by zylo117** [comment]
D7x takes 12G+ per image during training, but in dynamic graph framework like pytorch, it takes more, i.e. cache.
And I don't recommend training large network like D4+, it's just too slow. If you insist, you might have to try model parallel, to slice the network into pieces and place them across the gpus.

I think V100 16G is the worst product. It's super expensive and its great gpu core comes with only 16GB VRAM. What a waste. Even 3090 gets 24G.
VRAM is the most important resource in DL, not the gpu core.
