### ISSUE TITLE
关于训练自己数据集的错误

### ISSUE THREAD

**Issue by Zx-rqq** [zylo117/Yet-Another-EfficientDet-Pytorch#383]
loading annotations into memory...
Done (t=0.03s)
creating index...
index created!
loading annotations into memory...
Done (t=0.02s)
creating index...
index created!
initializing weights...
  0%|                                                                                                                    | 0/308 [00:00<?, ?it/s]111111111111   0%|                                                                                                                    | 0/308 [00:00<?, ?it/s]
Traceback (most recent call last):
  File "train.py", line 285, in <module>
    train(opt)
  File "train.py", line 162, in train
    for iter, data in enumerate(progress_bar):
  File "/usr/local/python3.7/lib/python3.7/site-packages/tqdm/_tqdm.py", line 1017, in __iter__
    for obj in iterable:
  File "/usr/local/python3.7/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 345, in __next__
    data = self._next_data()
  File "/usr/local/python3.7/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 856, in _next_data
    return self._process_data(data)
  File "/usr/local/python3.7/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 881, in _process_data
    data.reraise()
  File "/usr/local/python3.7/lib/python3.7/site-packages/torch/_utils.py", line 394, in reraise
    raise self.exc_type(msg)
**KeyError: Caught KeyError in DataLoader worker process 0.**
Original Traceback (most recent call last):
  File "/usr/local/python3.7/lib/python3.7/site-packages/torch/utils/data/_utils/worker.py", line 178, in _worker_loop
    data = fetcher.fetch(index)
  File "/usr/local/python3.7/lib/python3.7/site-packages/torch/utils/data/_utils/fetch.py", line 44, in fetch
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/usr/local/python3.7/lib/python3.7/site-packages/torch/utils/data/_utils/fetch.py", line 44, in <listcomp>
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/home/rqq/Yet-Another-EfficientDet-Pytorch-training-2/efficientdet/dataset.py", line 46, in __getitem__
    annot = self.load_annotations(idx)
  File "/home/rqq/Yet-Another-EfficientDet-Pytorch-training-2/efficientdet/dataset.py", line 78, in load_annotations
    annotation[0, 4] = self.coco_label_to_label(a['category_id'])
  File "/home/rqq/Yet-Another-EfficientDet-Pytorch-training-2/efficientdet/dataset.py", line 88, in coco_label_to_label
    return self.coco_labels_inverse[coco_label]
**KeyError: 2**

请指点一下，万分感谢

**Comment by zylo117** [comment]
I think you should update the code.
`coco_labels_inverse` should be removed a long time ago.
