### ISSUE TITLE
What happened，when i run with d0

### ISSUE THREAD

**Issue by jaguarzhang** [zylo117/Yet-Another-EfficientDet-Pytorch#391]
when i ran: batch size=12，COCO datasets，d0，and other configuration default

only one GPU

yet, the result is following.... 

loading annotations into memory...
Done (t=14.70s)
creating index...
index created!
loading annotations into memory...
Done (t=0.56s)
creating index...
index created!
[Info] initializing weights...
  0%|          | 1/19714 [00:00<1:09:47,  4.71it/s][Error] Traceback (most recent call last):
  File "E:/PycharmProjects/Yet-Another-EfficientDet-Pytorch/train.py", line 231, in train
    cls_loss, reg_loss = model(imgs, annot, obj_list=params.obj_list)
  File "D:\app\anaconda3\envs\Yet-Another-EfficientDet-Pytorch\lib\site-packages\torch\nn\modules\module.py", line 550, in __call__
    result = self.forward(*input, **kwargs)
  File "D:\app\anaconda3\envs\Yet-Another-EfficientDet-Pytorch\lib\site-packages\torch\nn\parallel\data_parallel.py", line 151, in forward
    inputs, kwargs = self.scatter(inputs, kwargs, self.device_ids)
  File "E:\PycharmProjects\Yet-Another-EfficientDet-Pytorch\utils\utils.py", line 208, in scatter
    for device_idx in range(len(devices))], \
  File "E:\PycharmProjects\Yet-Another-EfficientDet-Pytorch\utils\utils.py", line 208, in <listcomp>
    for device_idx in range(len(devices))], \
RuntimeError: CUDA error: invalid device ordinal

~~~~~~~~~~~~~~~~~~~~~~
so, what's the matter?  
Thanks~~~

**Comment by zylo117** [comment]
check num_gpus of your project yaml file. num_gpus <= physical_gpus

**Comment by jaguarzhang** [comment]
> check num_gpus of your project yaml file. num_gpus <= physical_gpus

thanks for your reply , and there is another problem:

when i  run tensorboard to get logs , the following occur: 

W0617 17:11:18.992393 30308 core_plugin.py:191] Unable to get first event timestamp for run tensorboard\20200615-144905: No event timestamp could be found
W0617 17:11:18.994389 30308 core_plugin.py:191] Unable to get first event timestamp for run tensorboard\20200615-145334: No event timestamp could be found
W0617 17:11:18.996383 30308 core_plugin.py:191] Unable to get first event timestamp for run tensorboard\20200615-145940: No event timestamp could be found
W0617 17:11:18.997380 30308 core_plugin.py:191] Unable to get first event timestamp for run tensorboard\20200615-150831: No event timestamp could be found
W0617 17:11:18.998378 30308 core_plugin.py:191] Unable to get first event timestamp for run tensorboard\20200617-145329: No event timestamp could be found
W0617 17:11:18.999376 30308 core_plugin.py:191] Unable to get first event timestamp for run tensorboard\20200617-145438: No event timestamp could be found
W0617 17:11:19.001370 30308 core_plugin.py:191] Unable to get first event timestamp for run tensorboard\20200617-145543: No event timestamp could be found

~~~~~~~~~~~~~~~~~~~~~~~~```
i search for the reason, but all that  do not work,,,
so, what can i should change for correct   ?   thanks @@~
