### ISSUE TITLE
Error while Inference on custom input image dimension?

### ISSUE THREAD

**Issue by shubhamsy777** [zylo117/Yet-Another-EfficientDet-Pytorch#406]
I am trying to do inference on efficientdet d1 model with a different input size say 480x270 (aspect ratio same as 1920x1080).  
Here is the input dimensions before passing it to model forward pass:
```
ori_imgs:  (270, 480, 3)  framed_imgs:  (480, 480, 3)  framed_metas:  (480, 270, 480, 270, 0, 210)
```

I get the following error: 

```
Traceback (most recent call last):
  File "test_detector_pt.py", line 55, in <module>
    bounding_boxes = detection_network.detect(batch_of_images)
  File "/data/sourabh/Releases/person_detector_tycoai/efficientdet_pt/detection_model.py", line 110, in detect
    features, regression, classification, anchors = self.model(x)
  File "/data/common_env/lib/python3.6/site-packages/torch/nn/modules/module.py", line 550, in __call__
    result = self.forward(*input, **kwargs)
  File "/data/sourabh/Releases/person_detector_tycoai/efficientdet_pt/backbone.py", line 68, in forward
    features = self.bifpn(features)
  File "/data/common_env/lib/python3.6/site-packages/torch/nn/modules/module.py", line 550, in __call__
    result = self.forward(*input, **kwargs)
  File "/data/common_env/lib/python3.6/site-packages/torch/nn/modules/container.py", line 100, in forward
    input = module(input)
  File "/data/common_env/lib/python3.6/site-packages/torch/nn/modules/module.py", line 550, in __call__
    result = self.forward(*input, **kwargs)
  File "/data/sourabh/Releases/person_detector_tycoai/efficientdet_pt/efficientdet/model.py", line 175, in forward
    p3_out, p4_out, p5_out, p6_out, p7_out = self._forward_fast_attention(inputs)
  File "/data/sourabh/Releases/person_detector_tycoai/efficientdet_pt/efficientdet/model.py", line 208, in _forward_fast_attention
    p5_up = self.conv5_up(self.swish(weight[0] * p5_in + weight[1] * self.p5_upsample(p6_up)))
RuntimeError: The size of tensor a (15) must match the size of tensor b (16) at non-singleton dimension 3
```  
However other dimension works like 512x288 etc. 
What is the rule to set the input image dimension? 
Will there be any accuracy hit?

**Comment by zylo117** [comment]
because 288 is 32 divisible. It must be 32 divisible.

**Comment by zylo117** [comment]
Its dimension must be 32 dividable
