### ISSUE TITLE
cv2.error: Caught error in DataLoader worker process 11. AND cvtColor ERROR

### ISSUE THREAD

**Issue by yunseokddi** [zylo117/Yet-Another-EfficientDet-Pytorch#422]
Hi. I'm doing a transfer learning on one label.
But it doesn't work well..
help me!
my cpu is 9th i5, gpu is rtx2070 super, and ram is 16G

`Step: 10. Epoch: 0/10. Iteration: 11/31. Cls loss: 2322.68164. Reg loss: 0.01680. Total loss: 2322.69849:
Traceback (most recent call last):
  File "train.py", line 331, in <module>
    train(opt)
  File "train.py", line 216, in train
    for iter, data in enumerate(progress_bar):
  File "/home/geosoft/.local/lib/python3.6/site-packages/tqdm/std.py", line 1129, in __iter__
    for obj in iterable:
  File "/home/geosoft/.local/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 345, in __next__
    data = self._next_data()
  File "/home/geosoft/.local/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 838, in _next_data
    return self._process_data(data)
  File "/home/geosoft/.local/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 881, in _process_data
    data.reraise()
  File "/home/geosoft/.local/lib/python3.6/site-packages/torch/_utils.py", line 395, in reraise
    raise self.exc_type(msg)
cv2.error: Caught error in DataLoader worker process 11.
Original Traceback (most recent call last):
  File "/home/geosoft/.local/lib/python3.6/site-packages/torch/utils/data/_utils/worker.py", line 178, in _worker_loop
    data = fetcher.fetch(index)
  File "/home/geosoft/.local/lib/python3.6/site-packages/torch/utils/data/_utils/fetch.py", line 44, in fetch
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/home/geosoft/.local/lib/python3.6/site-packages/torch/utils/data/_utils/fetch.py", line 44, in <listcomp>
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/home/geosoft/Desktop/Yet-Another-EfficientDet-Pytorch-master/efficientdet/dataset.py", line 42, in __getitem__
    img = self.load_image(idx)
  File "/home/geosoft/Desktop/Yet-Another-EfficientDet-Pytorch-master/efficientdet/dataset.py", line 54, in load_image
    img = cv2.cvtColor(img, cv2.COLOR_BGR2RGB)
cv2.error: OpenCV(4.2.0) /io/opencv/modules/imgproc/src/color.cpp:182: error: (-215:Assertion failed) !_src.empty() in function 'cvtColor'`

**Comment by zylo117** [comment]
datasets issue, empty images

**Comment by ManishDV** [comment]
I have the similar problem and apparently the dataset i am working with does not contain any empty images.  I have manually checked all the images.

Any Solutions???


Traceback (most recent call last):
  File "train.py", line 331, in <module>
    train(opt)
  File "train.py", line 273, in train
    for iter, data in enumerate(val_generator):
  File "/usr/local/lib/python3.6/dist-packages/torch/utils/data/dataloader.py", line 345, in __next__
    data = self._next_data()
  File "/usr/local/lib/python3.6/dist-packages/torch/utils/data/dataloader.py", line 856, in _next_data
    return self._process_data(data)
  File "/usr/local/lib/python3.6/dist-packages/torch/utils/data/dataloader.py", line 881, in _process_data
    data.reraise()
  File "/usr/local/lib/python3.6/dist-packages/torch/_utils.py", line 394, in reraise
    raise self.exc_type(msg)
cv2.error: Caught error in DataLoader worker process 0.
Original Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/torch/utils/data/_utils/worker.py", line 178, in _worker_loop
    data = fetcher.fetch(index)
  File "/usr/local/lib/python3.6/dist-packages/torch/utils/data/_utils/fetch.py", line 44, in fetch
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/usr/local/lib/python3.6/dist-packages/torch/utils/data/_utils/fetch.py", line 44, in <listcomp>
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/content/Yet-Another-EfficientDet-Pytorch/efficientdet/dataset.py", line 42, in __getitem__
    img = self.load_image(idx)
  File "/content/Yet-Another-EfficientDet-Pytorch/efficientdet/dataset.py", line 59, in load_image
    img = cv2.cvtColor(img, cv2.COLOR_BGR2RGB)
cv2.error: OpenCV(4.1.2) /io/opencv/modules/imgproc/src/color.cpp:182: error: (-215:Assertion failed) !_src.empty() in function 'cvtColor'

**Comment by yunseokddi** [comment]
I solve this problem. This error is datasets issue

**Comment by MHansy** [comment]
Hi Team

I am facing similar problem, On my side I'm training with gray scale images.....! Can it be a problem?

**Comment by jundongAI** [comment]
> I solve this problem. This error is datasets issue

Could you tell me what issue about the dataset？How did you deal with it？

**Comment by yunseokddi** [comment]
> > I solve this problem. This error is datasets issue
> 
> Could you tell me what issue about the dataset？How did you deal with it？

Check your image path

**Comment by jun214384468** [comment]
我的是在训练完一批进行验证的时候出现这种错误，训练数据与验证数据是一起弄得呀，验证需要在哪里改路径吗？
