### ISSUE TITLE
train problems

### ISSUE THREAD

**Issue by mytk2012** [zylo117/Yet-Another-EfficientDet-Pytorch#450]
My code stops at ltrain.py line 311:model.train for few hours.And my GPU memory remains at 371MB.But normally it should be 9700MB.I train it with D0 pre-trained weights.
![image](https://user-images.githubusercontent.com/57787557/88382585-55d86b80-cddb-11ea-82a3-e435db8a0e59.png)And my command line is:CUDA_VISIBLE_DEVICES=3,4,5 python train.py -c 0 -p coco --batch_size 16 --lr 1e-5 --num_epochs 100 --load_weights /home/pycharmprojects/EfficientDet/efficientdet-d0.pth

**Comment by zylo117** [comment]
Oh I see, I load the model to specified gpu starting from 0, instead of what you specified.

Maybe you can change it in the class CustomDataParallel.

**Comment by mytk2012** [comment]
> Oh I see, I load the model to specified gpu starting from 0, instead of what you specified.
> 
> Maybe you can change it in the class CustomDataParallel.

But I have tried CUDA_VISIBLE_DEVICES=0,1,2.It also fails.I did nothing but change datasets.Before that I can train normally.And my dataset class num are 4，which isn't beyond num_classes=80.

**Comment by mytk2012** [comment]
> Oh I see, I load the model to specified gpu starting from 0, instead of what you specified.
> 
> Maybe you can change it in the class CustomDataParallel.

Is it in touch with datasets size?

**Comment by zylo117** [comment]
Try running without specifying any gpu and make sure the GPUS in the project config suits your server.

**Comment by mytk2012** [comment]
> Try running without specifying any gpu and make sure the GPUS in the project config suits your server.

I have suceeded by editing CustomDataParallel！Thanks.But i don't know why I can't run cuda when I apply CUDA_VISIBLE_DEVICES=0,1,2. Maybe bad luck...And now,I can appoint the specified gpu.Thank you very much！

**Comment by zylo117** [comment]
Maybe you specify 3 gpus with environment variable but it's 4 gpus in config file.

**Comment by mytk2012** [comment]
> Maybe you specify 3 gpus with environment variable but it's 4 gpus in config file.
I'm afraid not.Because theses sesttings match each other.And when i restart the project,it don't run again.I guess maybe there are some limitations about cuda delay time(when you ctrll+C).

**Comment by zylo117** [comment]
How did you restart? With `-w last`?

**Comment by mytk2012** [comment]
> How did you restart? With `-w last`?
No,I ctrl+C.And run it again to validate whether it is normal.But unfortunately....

**Comment by mytk2012** [comment]
> How did you restart? With `-w last`?

command line::CUDA_VISIBLE_DEVICES=1,2,3 python train.py -c 0 -p coco --batch_size 16 --lr 1e-4 --load_weights /home/pycharmprojects/EfficientDet/efficientdet-d0.pth

**Comment by zylo117** [comment]
> > How did you restart? With `-w last`?
> 
> command line::CUDA_VISIBLE_DEVICES=1,2,3 python train.py -c 0 -p coco --batch_size 16 --lr 1e-4 --load_weights /home/pycharmprojects/EfficientDet/efficientdet-d0.pth

No, when you stop the process with ctrl+c, you need to change the line to ` --load_weights last` or a shorter one `-w last`

**Comment by lsfhuihuiff** [comment]
How much memory does it require when training custom datasets from scrach？there is always this kind of error——RuntimeError: DataLoader worker (pid(s) 29888, 16444, 21832) exited unexpectedly，when I train datasets.

**Comment by zylo117** [comment]
@lsfhuihuiff try reducing num_worker down to 0.

**Comment by lsfhuihuiff** [comment]
Can I change batch_size when I restart a training session?Thank you!

**Comment by zylo117** [comment]
yes, but the current epoch number could be changing

**Comment by lsfhuihuiff** [comment]
> yes, but the current epoch number could be changing

Thank you! But will this influence the training effect?

**Comment by zylo117** [comment]
it won't

**Comment by lsfhuihuiff** [comment]
Is there anyway that can solve this problem?Thank you!
using weights logs//face_detection/efficientdet-d1_350_178153.pth
Traceback (most recent call last):
  File "train.py", line 326, in <module>
    train(opt)
  File "train.py", line 139, in train
    ret = model.load_state_dict(torch.load(weights_path), strict=False)
  File "/headless/anaconda3/envs/pytorch/lib/python3.6/site-packages/torch/serialization.py", line 526, in load
    if _is_zipfile(opened_file):
  File "/headless/anaconda3/envs/pytorch/lib/python3.6/site-packages/torch/serialization.py", line 76, in _is_zipfile
    if ord(magic_byte) != ord(read_byte):
TypeError: ord() expected a character, but string of length 0 found

**Comment by lsfhuihuiff** [comment]
> Is there anyway that can solve this problem?Thank you!
> using weights logs//face_detection/efficientdet-d1_350_178153.pth
> Traceback (most recent call last):
> File "train.py", line 326, in
> train(opt)
> File "train.py", line 139, in train
> ret = model.load_state_dict(torch.load(weights_path), strict=False)
> File "/headless/anaconda3/envs/pytorch/lib/python3.6/site-packages/torch/serialization.py", line 526, in load
> if _is_zipfile(opened_file):
> File "/headless/anaconda3/envs/pytorch/lib/python3.6/site-packages/torch/serialization.py", line 76, in _is_zipfile
> if ord(magic_byte) != ord(read_byte):
> TypeError: ord() expected a character, but string of length 0 found

I have solved this problem,but new error occurred.         cuda error out of memory

**Comment by Complicateddd** [comment]
> > Is there anyway that can solve this problem?Thank you!
> > using weights logs//face_detection/efficientdet-d1_350_178153.pth
> > Traceback (most recent call last):
> > File "train.py", line 326, in
> > train(opt)
> > File "train.py", line 139, in train
> > ret = model.load_state_dict(torch.load(weights_path), strict=False)
> > File "/headless/anaconda3/envs/pytorch/lib/python3.6/site-packages/torch/serialization.py", line 526, in load
> > if _is_zipfile(opened_file):
> > File "/headless/anaconda3/envs/pytorch/lib/python3.6/site-packages/torch/serialization.py", line 76, in _is_zipfile
> > if ord(magic_byte) != ord(read_byte):
> > TypeError: ord() expected a character, but string of length 0 found
> 
> I have solved this problem,but new error occurred. cuda error out of memory

how to solve this problem that typeerror?

**Comment by zylo117** [comment]
@Complicateddd I think the weights are corrupted.
