### ISSUE TITLE
[Info] freezed backbone   0% 0/623 [00:00<?, ?it/s]Traceback (most recent call last):   File "train.py", line 326, in <module>

### ISSUE THREAD

**Issue by randallsalvares** [zylo117/Yet-Another-EfficientDet-Pytorch#471]
Hi please help, im getting the following issue while training my custom dataset

loading annotations into memory...
Done (t=1.56s)
creating index...
index created!
loading annotations into memory...
Done (t=0.12s)
creating index...
index created!
[Warning] Ignoring Error(s) in loading state_dict for EfficientDetBackbone:
	size mismatch for classifier.header.pointwise_conv.conv.weight: copying a param with shape torch.Size([810, 64, 1, 1]) from checkpoint, the shape in current model is torch.Size([9, 64, 1, 1]).
	size mismatch for classifier.header.pointwise_conv.conv.bias: copying a param with shape torch.Size([810]) from checkpoint, the shape in current model is torch.Size([9]).
[Warning] Don't panic if you see this, this might be because you load a pretrained weights with different number of classes. The rest of the weights should be loaded already.
[Info] loaded weights: efficientdet-d0.pth, resuming checkpoint from step: 0
[Info] freezed backbone
  0% 0/623 [00:00<?, ?it/s]Traceback (most recent call last):
  File "train.py", line 326, in <module>
    train(opt)
  File "train.py", line 211, in train
    for iter, data in enumerate(progress_bar):
  File "/usr/local/lib/python3.6/dist-packages/tqdm/std.py", line 1104, in __iter__
    for obj in iterable:
  File "/usr/local/lib/python3.6/dist-packages/torch/utils/data/dataloader.py", line 345, in __next__
    data = self._next_data()
  File "/usr/local/lib/python3.6/dist-packages/torch/utils/data/dataloader.py", line 856, in _next_data
    return self._process_data(data)
  File "/usr/local/lib/python3.6/dist-packages/torch/utils/data/dataloader.py", line 881, in _process_data
    data.reraise()
  File "/usr/local/lib/python3.6/dist-packages/torch/_utils.py", line 394, in reraise
    raise self.exc_type(msg)
KeyError: Caught KeyError in DataLoader worker process 0.
Original Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/torch/utils/data/_utils/worker.py", line 178, in _worker_loop
    data = fetcher.fetch(index)
  File "/usr/local/lib/python3.6/dist-packages/torch/utils/data/_utils/fetch.py", line 44, in fetch
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/usr/local/lib/python3.6/dist-packages/torch/utils/data/_utils/fetch.py", line 44, in <listcomp>
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/content/drive/My Drive/Yet-Another-EfficientDet-Pytorch-master/efficientdet/dataset.py", line 42, in __getitem__
    img = self.load_image(idx)
  File "/content/drive/My Drive/Yet-Another-EfficientDet-Pytorch-master/efficientdet/dataset.py", line 50, in load_image
    image_info = self.coco.loadImgs(self.image_ids[image_index])[0]
  File "/usr/local/lib/python3.6/dist-packages/pycocotools/coco.py", line 229, in loadImgs
    return [self.imgs[id] for id in ids]
  File "/usr/local/lib/python3.6/dist-packages/pycocotools/coco.py", line 229, in <listcomp>
    return [self.imgs[id] for id in ids]
KeyError: 'f'

**Comment by zylo117** [comment]
https://github.com/zylo117/Yet-Another-EfficientDet-Pytorch/issues/351#issuecomment-636343289

**Comment by randallsalvares** [comment]
@zylo117  Thank you!
