### ISSUE TITLE
TypeError: an integer is required (got type tuple)

### ISSUE THREAD

**Issue by Usenameis** [zylo117/Yet-Another-EfficientDet-Pytorch#479]
Traceback (most recent call last):
  File "D:/code/Yet-Another-EfficientDet-Pytorch-master/efficientdet_test.py", line 102, in <module>
    display(out, ori_imgs, imshow=False, imwrite=True)
  File "D:/code/Yet-Another-EfficientDet-Pytorch-master/efficientdet_test.py", line 90, in display
    plot_one_box(imgs[i], [x1, y1, x2, y2], label=obj,score=score,color=color_list[get_index_label(obj, obj_list)])
  File "D:\code\Yet-Another-EfficientDet-Pytorch-master\utils\utils.py", line 295, in plot_one_box
    cv2.rectangle(img, c1, c2, color, thickness=tl)
TypeError: an integer is required (got type tuple)
--------------------------------------------------------
I run the code with efficientdef-d7 ,and code is not modified.How to solve this problem.....

**Comment by zylo117** [comment]
Sorry for the trouble, it should be fixed.
https://github.com/zylo117/Yet-Another-EfficientDet-Pytorch/commit/b349ef0de86ec52742ecc46cbd9059ec3f5edb1b
