### ISSUE TITLE
efficientdet-d8.pth RuntimeError: The size of tensor a (11) must match the size of tensor b (12) 

### ISSUE THREAD

**Issue by xzswater** [zylo117/Yet-Another-EfficientDet-Pytorch#484]
[Info] loaded weights: efficientdet-d8.pth, resuming checkpoint from step: 0

[Error] Traceback (most recent call last):
  File "train.py", line 228, in train
    cls_loss, reg_loss = model(imgs, annot, obj_list=params.obj_list)
  File "/ssd1/zhangsan/2d_detection/obs_2d_detect/pyenv/lib/python3.6/site-packages/torch/nn/modules/module.py", line 532, in __call__
    result = self.forward(*input, **kwargs)
  File "train.py", line 77, in forward
    _, regression, classification, anchors = self.model(imgs)
  File "/ssd1/zhangsan/2d_detection/obs_2d_detect/pyenv/lib/python3.6/site-packages/torch/nn/modules/module.py", line 532, in __call__
    result = self.forward(*input, **kwargs)
  File "/ssd1/zhangsan/2d_detection/obs_2d_detect/EfficientDet/backbone.py", line 73, in forward
    features = self.bifpn(features)
  File "/ssd1/zhangsan/2d_detection/obs_2d_detect/pyenv/lib/python3.6/site-packages/torch/nn/modules/module.py", line 532, in __call__
    result = self.forward(*input, **kwargs)
  File "/ssd1/zhangsan/2d_detection/obs_2d_detect/pyenv/lib/python3.6/site-packages/torch/nn/modules/container.py", line 100, in forward
    input = module(input)
  File "/ssd1/zhangsan/2d_detection/obs_2d_detect/pyenv/lib/python3.6/site-packages/torch/nn/modules/module.py", line 532, in __call__
    result = self.forward(*input, **kwargs)
  File "/ssd1/zhangsan/2d_detection/obs_2d_detect/EfficientDet/efficientdet/model.py", line 190, in forward
    outs = self._forward(inputs)
  File "/ssd1/zhangsan/2d_detection/obs_2d_detect/EfficientDet/efficientdet/model.py", line 293, in _forward
    p7_up = self.conv7_up(self.swish(p7_in + self.p7_upsample(p8_in)))
RuntimeError: The size of tensor a (11) must match the size of tensor b (12) at non-singleton dimension 3

**Comment by xzswater** [comment]
train.py
L112  input_sizes = [512, 640, 768, 896, 1024, 1280, 1280, 1536, 1356]
modify the last item, 1356 to 1536, solve the probelm.

**Comment by zylo117** [comment]
fixed.
https://github.com/zylo117/Yet-Another-EfficientDet-Pytorch/commit/fb9cd2466685d530a0860119fe980def35ff33e2#diff-e44f4a60e89e820dde9bb27afa634965
