### ISSUE TITLE
can not load model weights

### ISSUE THREAD

**Issue by wanghuajia** [zylo117/Yet-Another-EfficientDet-Pytorch#51]
Thanks for sharing your code. When I loaded the code weights, I found that the dimensions were wrong, but I strictly followed your code to load, I would like to ask
![image](https://user-images.githubusercontent.com/35687444/79110249-9a03ab00-7dac-11ea-94f9-69cd1a1b5d68.png)

**Comment by zylo117** [comment]
Please provide more info

**Comment by wanghuajia** [comment]
> Please provide more info

OK, as shown above

**Comment by zylo117** [comment]
There is no method or function named 'get_net' in this repo.

**Comment by prfans** [comment]
You can try this.

state_dict = torch.load(weights_path)
state_dict.pop('classifier .header . pointwise_ conv . conv . weight')
state_dict.pop('classifier .header . pointwise conv. conv. bias')
model.load_state_dict(state_dict, strict=False)

**Comment by plusczh** [comment]
check `num_classes` or `obj_list`

**Comment by xtzd** [comment]
I guess you use your own dataset but you wanted to use pretrained model. The point is num_classes is not the same. According to your issues, your dataset seems to have 7 classes, but coco pretrained model have 80 classes. Maybe you can try to use only the backbone.

**Comment by zylo117** [comment]
It doesn't matter, the training program will skip the classifier's header if num_classes don't match while loading weights.

**Comment by BenBerCao** [comment]
I used my own data to train(two classes) and got similar problem:

Traceback (most recent call last):
  File "coco_eval.py", line 156, in <module>
    model.load_state_dict(torch.load(weights_path, map_location=torch.device('cpu')))
  File "C:\Users\ASUS\Anaconda3\envs\pytorch-gpu\lib\site-packages\torch\nn\modules\module.py", line 830, in load_state_dict
    self.__class__.__name__, "\n\t".join(error_msgs)))
RuntimeError: Error(s) in loading state_dict for EfficientDetBackbone:

It confused me,how to solve this?

**Comment by zylo117** [comment]
pls provide more info

**Comment by BenBerCao** [comment]
Thank you for your reply

Traceback (most recent call last):
  File "coco_eval.py", line 156, in <module>
    model.load_state_dict(torch.load(weights_path, map_location=torch.device('cpu')))
  File "C:\Users\ASUS\Anaconda3\envs\pytorch-gpu\lib\site-packages\torch\nn\modules\module.py", line 830, in load_state_dict
    self.__class__.__name__, "\n\t".join(error_msgs)))
RuntimeError: Error(s) in loading state_dict for EfficientDetBackbone:
        Missing key(s) in state_dict: "bifpn.4.p6_w1", "bifpn.4.p5_w1", "bifpn.4.p4_w1", "bifpn.4.p3_w1", "bifpn.4.p4_w2", "bifpn.4.p5_w2", "bifpn.4.p6_w2", "bifpn.4.p7_w2", "bifpn.4.conv6_up.depthwise_conv.conv.weight", "bifpn.4.conv6_up.pointwise_conv.conv.weight", "bifpn.4.conv6_up.pointwise_conv.conv.bias", "bifpn.4.conv6_up.bn.weight", "bifpn.4.conv6_up.bn.bias", "bifpn.4.conv6_up.bn.running_mean", "bifpn.4.conv6_up.bn.running_var", "bifpn.4.conv5_up.depthwise_conv.conv.weight", "bifpn.4.conv5_up.pointwise_conv.conv.weight", "bifpn.4.conv5_up.pointwise_conv.conv.bias", "bifpn.4.conv5_up.bn.weight", "bifpn.4.conv5_up.bn.bias", "bifpn.4.conv5_up.bn.running_mean", "bifpn.4.conv5_up.bn.running_var", "bifpn.4.conv4_up.depthwise_conv.conv.weight", "bifpn.4.conv4_up.pointwise_conv.conv.weight", "bifpn.4.conv4_up.pointwise_conv.conv.bias", "bifpn.4.conv4_up.bn.weight", "bifpn.4.conv4_up.bn.bias", "bifpn.4.conv4_up.bn.running_mean", "bifpn.4.conv4_up.bn.running_var", "bifpn.4.conv3_up.depthwise_conv.conv.weight", "bifpn.4.conv3_up.pointwise_conv.conv.weight", "bifpn.4.conv3_up.pointwise_conv.conv.bias", "bifpn.4.conv3_up.bn.weight", "bifpn.4.conv3_up.bn.bias", "bifpn.4.conv3_up.bn.running_mean", "bifpn.4.conv3_up.bn.running_var", "bifpn.4.conv4_down.depthwise_conv.conv.weight", "bifpn.4.conv4_down.pointwise_conv.conv.weight", "bifpn.4.conv4_down.pointwise_conv.conv.bias", "bifpn.4.conv4_down.bn.weight", "bifpn.4.conv4_down.bn.bias", "bifpn.4.conv4_down.bn.running_mean", "bifpn.4.conv4_down.bn.running_var", "bifpn.4.conv5_down.depthwise_conv.conv.weight", "bifpn.4.conv5_down.pointwise_conv.conv.weight", "bifpn.4.conv5_down.pointwise_conv.conv.bias",

the rest is too long 
this happened when I run coco_eval.py(used the model I trained)

**Comment by qtw1998** [comment]
> pls provide more info
@BenBerCao I met the same problems @wanghuajia

**Comment by BenBerCao** [comment]
> > pls provide more info
> > @BenBerCao I met the same problems @wanghuajia

I tried auther's EfficientDet Training On A Custom Dataset(https://github.com/zylo117/Yet-Another-EfficientDet-Pytorch/blob/master/tutorial/train_shape.ipynb) , I trained  it and evalled successfully, However,when I evalled my own model ,I still have this problem, if you have any solutions,please reply to me,thanks a lot.

**Comment by ManojKesani** [comment]
> > > pls provide more info
> > > @BenBerCao I met the same problems @wanghuajia
> 
> I tried auther's EfficientDet Training On A Custom Dataset(https://github.com/zylo117/Yet-Another-EfficientDet-Pytorch/blob/master/tutorial/train_shape.ipynb) , I trained it and evalled successfully, However,when I evalled my own model ,I still have this problem, if you have any solutions,please reply to me,thanks a lot.

i met the same problem as well, 
After training on a custom dataset with 2 objects . I used the efficientdet_test_video.py script to test the models. D0 seems to work fine but D1,D2,.. gives this error.

**Comment by williamscott701** [comment]
any fix?

**Comment by zylo117** [comment]
you need to specify the network architecture before inference, loading a d1 weights into a d0 network is not possible

**Comment by ManojKesani** [comment]
Go through your imports , some where in them you might be still using d0 rather than d1,d2....
Change it as required and it might solve this.

**Comment by williamscott701** [comment]
> Go through your imports , some where in them you might be still using d0 rather than d1,d2....
> Change it as required and it might solve this.

Found it, Thank you ;)

**Comment by fardinadii** [comment]
Hi all, 
I have the same problem and I could not find a way to solve it. I downloaded efficiendet_d0.pth and I want to use d0.  @williamscott701 @ManojKesani

**Comment by ManojKesani** [comment]
It's been a while since I used this, as far as I remember you need to go through the 8mpots and somewhere in those scripts there will be places u need to change the model u want. Hope this helps

**Comment by ManojKesani** [comment]
> It's been a while since I used this, as far as I remember you need to go through the impots and somewhere in those scripts there will be places u need to change the model u want. Hope this helps

**Comment by ManojKesani** [comment]
> Hi all, 
> I have the same problem and I could not find a way to solve it. I downloaded efficiendet_d0.pth and I want to use d0.  @williamscott701 @ManojKesani 

It's been a while since I used this, as far as I remember you need to go through the impots and somewhere in those scripts there will be places u need to change the model u want. Hope this helps.

**Comment by fardinadii** [comment]
> > Hi all,
> > I have the same problem and I could not find a way to solve it. I downloaded efficiendet_d0.pth and I want to use d0.  @williamscott701 @ManojKesani
> 
> It's been a while since I used this, as far as I remember you need to go through the impots and somewhere in those scripts there will be places u need to change the model u want. Hope this helps.

thank you so much @ManojKesani

**Comment by fardinadii** [comment]
> Hi all, I have the same problem and I could not find a way to solve it. I downloaded efficiendet_d0.pth and I want to use d0. @williamscott701 @ManojKesani

Hi all, i find the problem. This error rise when we use wrong image size. for me i should set image size to 512 to run without any error.
