### ISSUE TITLE
ZeroDivisionError : Training on custom dataset

### ISSUE THREAD

**Issue by Siddhijain16** [zylo117/Yet-Another-EfficientDet-Pytorch#517]
Hi @zylo117 ,
I am using the pretrained weight "efficientdet-d0.pth" for training of my own dataset . As I start training I faced ZeroDivisionError.
I checked in other issues but couldn't find anything .Please help me to fix this.

Error:

loading annotations into memory...
Done (t=0.01s)
creating index...
index created!
loading annotations into memory...
Done (t=0.00s)
creating index...
index created!
[Warning] Ignoring Error(s) in loading state_dict for EfficientDetBackbone:
	size mismatch for classifier.header.pointwise_conv.conv.weight: copying a param with shape torch.Size([810, 64, 1, 1]) from checkpoint, the shape in current model is torch.Size([36, 64, 1, 1]).
	size mismatch for classifier.header.pointwise_conv.conv.bias: copying a param with shape torch.Size([810]) from checkpoint, the shape in current model is torch.Size([36]).
[Warning] Don't panic if you see this, this might be because you load a pretrained weights with different number of classes. The rest of the weights should be loaded already.
[Info] loaded weights: efficientdet-d0.pth, resuming checkpoint from step: 0
Traceback (most recent call last):
  File "train.py", line 326, in <module>
    train(opt)
  File "train.py", line 205, in train
    last_epoch = step // num_iter_per_epoch
ZeroDivisionError: integer division or modulo by zero

![image](https://user-images.githubusercontent.com/46879959/95748929-669ccd00-0cb8-11eb-89c8-2657fc553214.png)

**Comment by guangkaixu** [comment]
num_iter_per_epoch means length of training_generator, check if your traning_set is empty. (I guessed, cuz the loading time is too short, comparing to my 30s on GTX950M)

**Comment by Siddhijain16** [comment]
Thank you @guangkaixu for your reply.I checked everthing and also my training_set is not empty. Still I am unable to figure out what's the root cause of this error..

**Comment by Siddhijain16** [comment]
Hi @zylo117 ,
I tried many thing from my end to resolve this error but nothing work for me . The main problem is in the loading of dataset, as it is not loading my training images which results in the "num_iter_per_epoch  0" in train.py file whereas inside my train folder I have total 940 images. 
Can u suggest something for me what should I do..
![image](https://user-images.githubusercontent.com/46879959/95960139-007f8980-0e21-11eb-9d99-58d88f27071d.png)

**Comment by zylo117** [comment]
What your training command?

**Comment by zylo117** [comment]
And where is your dataset? Is it {project_root}/datasets/{project_name}/{train}*/a.jpg? And are they included in your project.yml file?

**Comment by Siddhijain16** [comment]
My training command -
 !python train.py -c 0 -p signnet --batch_size 12  --lr 1e-5 --num_epochs 1000 \
 --load_weights ./weights/efficientdet-d0.pth


> And where is your dataset? Is it {project_root}/datasets/{project_name}/{train}*/a.jpg? And are they included in your project.yml file?
Yes ,My dataset is in {project_root}/datasets/{project_name}/{train}*/a.jpg structure and it is included in my project.yml file

**Comment by zylo117** [comment]
So you have less than 12 images?

**Comment by Siddhijain16** [comment]
No I have more than 900 images for my training set

**Comment by zylo117** [comment]
why don't you comment the related three lines from line 205 and see what will happen

**Comment by Siddhijain16** [comment]
> why don't you comment the related three lines from line 205 and see what will happen

As you suggested I did and got this 

![ss](https://user-images.githubusercontent.com/46879959/96407489-1b764300-11ff-11eb-996d-442760a21ec8.JPG)

**Comment by zylo117** [comment]
it seems there was no input at all. I think there is something wrong with your dataset or your annotations.
