### ISSUE TITLE
AttributeError: 'DataParallel' object has no attribute 'model'

### ISSUE THREAD

**Issue by jun214384468** [zylo117/Yet-Another-EfficientDet-Pytorch#523]
[Info] loaded weights: efficientdet-d2.pth, resuming checkpoint from step: 0
Step: 499. Epoch: 0/1000. Iteration: 500/580. Cls loss: 2.06874. Reg loss: 3.36804. Total loss: 5.43678:  86%|█████████████████▏  | 499/580 [07:56<01:14,  1.08it/s][Error] Traceback (most recent call last):
  File "train.py", line 257, in train
    save_checkpoint(model, f'efficientdet-d{opt.compound_coef}_{epoch}_{step}.pth')
  File "train.py", line 323, in save_checkpoint
    torch.save(model.model.state_dict(), os.path.join(opt.saved_path, name))
  File "/home/yjh/.conda/envs/yjh_torch/lib/python3.6/site-packages/torch/nn/modules/module.py", line 539, in __getattr__
    type(self).__name__, name))
AttributeError: 'DataParallel' object has no attribute 'model'
这是什么原因造成的呢？

**Comment by zylo117** [comment]
What's your pytorch version? I tested it under 1.4 and 1.5.

**Comment by jun214384468** [comment]
> What's your pytorch version? I tested it under 1.4 and 1.5.

# CUDA 9.0
conda install pytorch==1.1.0 torchvision==0.3.0 cudatoolkit=9.0 -c pytorch
这是我的环境

**Comment by jun214384468** [comment]
> > What's your pytorch version? I tested it under 1.4 and 1.5.
> 
> # CUDA 9.0
> conda install pytorch==1.1.0 torchvision==0.3.0 cudatoolkit=9.0 -c pytorch
> 这是我的环境

这个跟版本好像没有关系，我把模型保存那一块代码换了一下，这个问题解决啦，谢谢你
