### ISSUE TITLE
can not load image after first epoch

### ISSUE THREAD

**Issue by Cleehao** [zylo117/Yet-Another-EfficientDet-Pytorch#530]
At first, I thought it was an open CV problem. Later, it was changed to PIL to read the image, or did it report an error
![Y19YD553K3R$N5(%54PZEPO](https://user-images.githubusercontent.com/64185004/96719324-d3604780-13db-11eb-87a6-ecb9400d9e60.png)

**Comment by Cleehao** [comment]
![Y19YD553K3R$N5(%54PZEPO](https://user-images.githubusercontent.com/64185004/96719429-f4289d00-13db-11eb-9bb2-19d91b7b0fa1.png)

**Comment by Cleehao** [comment]
datasets/coco
loading annotations into memory...
Done (t=0.47s)
creating index...
index created!
loading annotations into memory...
Done (t=14.16s)
creating index...
index created!
[Info] loaded weights: efficientdet-d0.pth, resuming checkpoint from step: 0
[Info] freezed backbone
Step: 103. Epoch: 0/2. Iteration: 104/104. Cls loss: 0.31906. Reg loss: 1.51322. Total loss: 1.83227: 100% 104/104 [03:48<00:00,  2.20s/it]
Traceback (most recent call last):
  File "train.py", line 331, in <module>
    train(opt)
  File "train.py", line 272, in train
    for iter, data in enumerate(val_generator):
  File "/usr/local/lib/python3.6/dist-packages/torch/utils/data/dataloader.py", line 345, in __next__
    data = self._next_data()
  File "/usr/local/lib/python3.6/dist-packages/torch/utils/data/dataloader.py", line 385, in _next_data
    data = self._dataset_fetcher.fetch(index)  # may raise StopIteration
  File "/usr/local/lib/python3.6/dist-packages/torch/utils/data/_utils/fetch.py", line 44, in fetch
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/usr/local/lib/python3.6/dist-packages/torch/utils/data/_utils/fetch.py", line 44, in <listcomp>
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/content/gdrive/My Drive/et/efficientdet/dataset.py", line 52, in __getitem__
    img = self.load_image(idx)
  File "/content/gdrive/My Drive/et/efficientdet/dataset.py", line 67, in load_image
    img=Image.open(path)
  File "/usr/local/lib/python3.6/dist-packages/PIL/Image.py", line 2809, in open
    fp = builtins.open(filename, "rb")
FileNotFoundError: [Errno 2] No such file or directory: 'datasets/coco/val2017/000000391895.jpg'

**Comment by zylo117** [comment]
Can you make sure that the images of val set exist in that filepath and the filepath contains nothing but ascii characters?
You may also suffer rgb/bgr issue when using pil.

**Comment by Cleehao** [comment]
> Can you make sure that the images of val set exist in that filepath and the filepath contains nothing but ascii characters?
> You may also suffer rgb/bgr issue when using pil.
My path is / content / GDrive / my drive / et / datasets / coco / train2017, and the dataset is indeed in the path (for quick verification, I exchanged the training set with the verification set), and I checked that there was only ASCII characters in it. The PIL is modified to read the image and convert it into BGR format. In addition, when I use OpenCV to read the image, cv2error is reported, as shown below

**Comment by Cleehao** [comment]
> Can you make sure that the images of val set exist in that filepath and the filepath contains nothing but ascii characters?
> You may also suffer rgb/bgr issue when using pil.
datasets/coco
loading annotations into memory...
Done (t=0.47s)
creating index...
index created!
loading annotations into memory...
Done (t=14.82s)
creating index...
index created!
[Info] loaded weights: efficientdet-d0.pth, resuming checkpoint from step: 0
[Info] freezed backbone
Step: 103. Epoch: 0/2. Iteration: 104/104. Cls loss: 0.28095. Reg loss: 1.65669. Total loss: 1.93764: 100% 104/104 [01:30<00:00,  1.15it/s]
Traceback (most recent call last):
  File "train.py", line 331, in <module>
    train(opt)
  File "train.py", line 272, in train
    for iter, data in enumerate(val_generator):
  File "/usr/local/lib/python3.6/dist-packages/torch/utils/data/dataloader.py", line 345, in __next__
    data = self._next_data()
  File "/usr/local/lib/python3.6/dist-packages/torch/utils/data/dataloader.py", line 856, in _next_data
    return self._process_data(data)
  File "/usr/local/lib/python3.6/dist-packages/torch/utils/data/dataloader.py", line 881, in _process_data
    data.reraise()
  File "/usr/local/lib/python3.6/dist-packages/torch/_utils.py", line 394, in reraise
    raise self.exc_type(msg)
cv2.error: Caught error in DataLoader worker process 0.
Original Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/torch/utils/data/_utils/worker.py", line 178, in _worker_loop
    data = fetcher.fetch(index)
  File "/usr/local/lib/python3.6/dist-packages/torch/utils/data/_utils/fetch.py", line 44, in fetch
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/usr/local/lib/python3.6/dist-packages/torch/utils/data/_utils/fetch.py", line 44, in <listcomp>
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/content/gdrive/My Drive/et/efficientdet/dataset.py", line 52, in __getitem__
    img = self.load_image(idx)
  File "/content/gdrive/My Drive/et/efficientdet/dataset.py", line 66, in load_image
    img = cv2.cvtColor(img,cv2.COLOR_BGR2RGB)
cv2.error: OpenCV(4.1.2) /io/opencv/modules/imgproc/src/color.cpp:182: error: (-215:Assertion failed) !_src.empty() in function 'cvtColor'

**Comment by zylo117** [comment]
I think there is something wrong with your annotations. I have coco2017 myself, but I don't have `val2017/000000391895.jpg`

**Comment by Cleehao** [comment]
> I think there is something wrong with your datasets. I have coco2017 myself, but I don't have `val2017/000000391895.jpg`

Thank you. The problem has been solved. The main reason is that I forgot to add trainset and valset at the same time

**Comment by 1984chen** [comment]
> > I think there is something wrong with your datasets. I have coco2017 myself, but I don't have `val2017/000000391895.jpg`
> 
> Thank you. The problem has been solved. The main reason is that I forgot to add trainset and valset at the same time

hello, i have met the same problem, could you please tell me where to add the train_set and val_set? in xx.yml? thanks a lot.
