### ISSUE TITLE
KeyError: '1'  

### ISSUE THREAD

**Issue by zhangddac** [zylo117/Yet-Another-EfficientDet-Pytorch#566]
Step: 71. Epoch: 0/50. Iteration: 72/72. Cls loss: 1226.72363. Reg loss: 4.96134. Total loss: 1231.68494: 100%|██████████| 72/72 [00:54<00:00,  1.31it/s]
Traceback (most recent call last):
  File "C:/Programs/python/pycharm/object_detection/ptroch efficientdet/Yet-Another-EfficientDet-Pytorch-master/train.py", line 326, in <module>
    train(opt)
  File "C:/Programs/python/pycharm/object_detection/ptroch efficientdet/Yet-Another-EfficientDet-Pytorch-master/train.py", line 268, in train
    for iter, data in enumerate(val_generator):
  File "C:\Users\z1171\anaconda3\lib\site-packages\torch\utils\data\dataloader.py", line 435, in __next__
    data = self._next_data()
  File "C:\Users\z1171\anaconda3\lib\site-packages\torch\utils\data\dataloader.py", line 1085, in _next_data
    return self._process_data(data)
  File "C:\Users\z1171\anaconda3\lib\site-packages\torch\utils\data\dataloader.py", line 1111, in _process_data
    data.reraise()
  File "C:\Users\z1171\anaconda3\lib\site-packages\torch\_utils.py", line 428, in reraise
    raise self.exc_type(msg)
KeyError: Caught KeyError in DataLoader worker process 0.
Original Traceback (most recent call last):
  File "C:\Users\z1171\anaconda3\lib\site-packages\torch\utils\data\_utils\worker.py", line 198, in _worker_loop
    data = fetcher.fetch(index)
  File "C:\Users\z1171\anaconda3\lib\site-packages\torch\utils\data\_utils\fetch.py", line 44, in fetch
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "C:\Users\z1171\anaconda3\lib\site-packages\torch\utils\data\_utils\fetch.py", line 44, in <listcomp>
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "C:\Programs\python\pycharm\object_detection\ptroch efficientdet\Yet-Another-EfficientDet-Pytorch-master\efficientdet\dataset.py", line 42, in __getitem__
    img = self.load_image(idx)
  File "C:\Programs\python\pycharm\object_detection\ptroch efficientdet\Yet-Another-EfficientDet-Pytorch-master\efficientdet\dataset.py", line 50, in load_image
    image_info = self.coco.loadImgs(self.image_ids[image_index])[0]
  File "C:\Users\z1171\anaconda3\lib\site-packages\pycocotools\coco.py", line 230, in loadImgs
    return [self.imgs[id] for id in ids]
  File "C:\Users\z1171\anaconda3\lib\site-packages\pycocotools\coco.py", line 230, in <listcomp>
    return [self.imgs[id] for id in ids]
KeyError: '1'

Process finished with exit code 1

**Comment by zylo117** [comment]
It seems your dataset is not in the correct coco format.

**Comment by zhangddac** [comment]
> It seems your dataset is not in the correct coco format.

Do you mind sharing how your own coco dataset is made?

**Comment by zylo117** [comment]
1. make sure image ids are ints, not strings.
2. category id starts from 1.

**Comment by zylo117** [comment]
I can help train the dataset for you, if you don't mind sharing the dataset.

**Comment by zhangddac** [comment]
Thank you very much for helping me train, but my data set cannot be shared, so sorry. The format of my data set is voc. I tried some methods to convert it to coco format, but it always fails to train normally.

**Comment by zylo117** [comment]
Indeed, I tried converting some voc format datasets, xml format labels for every image are not easy to handle.

**Comment by zhangddac** [comment]
I once read your article on Zhihu and it is very good.
