### ISSUE TITLE
Key error: categories

### ISSUE THREAD

**Issue by keerthi4399** [zylo117/Yet-Another-EfficientDet-Pytorch#577]
loading annotations into memory...
Done (t=0.00s)
creating index...
index created!
Traceback (most recent call last):
  File "train.py", line 326, in <module>
    train(opt)
  File "train.py", line 116, in train
    Resizer(input_sizes[opt.compound_coef])]))
  File "/content/drive/MyDrive/30dec2020/Yet-Another-EfficientDet-Pytorch/efficientdet/dataset.py", line 20, in __init__
    self.load_classes()
  File "/content/drive/MyDrive/30dec2020/Yet-Another-EfficientDet-Pytorch/efficientdet/dataset.py", line 25, in load_classes
    categories = self.coco.loadCats(self.coco.getCatIds())
  File "/usr/local/lib/python3.6/dist-packages/pycocotools/coco.py", line 171, in getCatIds
    cats = self.dataset['categories']
KeyError: 'categories'

when I am training for custom dataset, getting this error. Please let me know. Thank you!

**Comment by zylo117** [comment]
You can refer to those few datasets for tutorial in the release page.
![image](https://user-images.githubusercontent.com/5842006/103543768-02b22b00-4eda-11eb-8eae-adf090fbc900.png)

**Comment by keerthi4399** [comment]
could you specify where should add this block of code?
Thank you!

**Comment by zylo117** [comment]
it's a key of the main level.
you should download one of the datasets and see it for yourself

**Comment by keerthi4399** [comment]
Thanks, I'll check it out.
