### ISSUE TITLE
KeyError: 'iscrowd'

### ISSUE THREAD

**Issue by Goki-0324** [zylo117/Yet-Another-EfficientDet-Pytorch#654]
I had below error when training with my dataset.

Traceback (most recent call last):
  File "train.py", line 326, in <module>
    train(opt)
  File "train.py", line 211, in train
    for iter, data in enumerate(progress_bar):
  File "C:\ProgramData\Anaconda3\envs\py3-TF2.0\lib\site-packages\tqdm\std.py", line 1129, in __iter__
    for obj in iterable:
  File "C:\ProgramData\Anaconda3\envs\py3-TF2.0\lib\site-packages\torch\utils\data\dataloader.py", line 517, in __next__
    data = self._next_data()
  File "C:\ProgramData\Anaconda3\envs\py3-TF2.0\lib\site-packages\torch\utils\data\dataloader.py", line 1199, in _next_data
    return self._process_data(data)
  File "C:\ProgramData\Anaconda3\envs\py3-TF2.0\lib\site-packages\torch\utils\data\dataloader.py", line 1225, in _process_data
    data.reraise()
  File "C:\ProgramData\Anaconda3\envs\py3-TF2.0\lib\site-packages\torch\_utils.py", line 429, in reraise
    raise self.exc_type(msg)
KeyError: Caught KeyError in DataLoader worker process 0.
Original Traceback (most recent call last):
  File "C:\ProgramData\Anaconda3\envs\py3-TF2.0\lib\site-packages\torch\utils\data\_utils\worker.py", line 202, in _worker_loop
    data = fetcher.fetch(index)
  File "C:\ProgramData\Anaconda3\envs\py3-TF2.0\lib\site-packages\torch\utils\data\_utils\fetch.py", line 44, in fetch
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "C:\ProgramData\Anaconda3\envs\py3-TF2.0\lib\site-packages\torch\utils\data\_utils\fetch.py", line 44, in <listcomp>
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "C:\Users\NEC-PCuser\projects\efficientdet\dataset.py", line 43, in __getitem__
    annot = self.load_annotations(idx)
  File "C:\Users\NEC-PCuser\projects\efficientdet\dataset.py", line 59, in load_annotations
    annotations_ids = self.coco.getAnnIds(imgIds=self.image_ids[image_index], iscrowd=False)
  File "C:\ProgramData\Anaconda3\envs\py3-TF2.0\lib\site-packages\pycocotools\coco.py", line 153, in getAnnIds
    ids = [ann['id'] for ann in anns if ann['iscrowd'] == iscrowd]
  File "C:\ProgramData\Anaconda3\envs\py3-TF2.0\lib\site-packages\pycocotools\coco.py", line 153, in <listcomp>
    ids = [ann['id'] for ann in anns if ann['iscrowd'] == iscrowd]
KeyError: 'iscrowd'

How may I solve this?
I will very much appreciate your advice.

**Comment by zylo117** [comment]
Your dataset is missing key iscrowd?

**Comment by Goki-0324** [comment]
Thank you very much for the reply.
Yes, I put iscrowd key like 'iscrowd':0.
I also tried with ‘iscrowd’:1 just in case but had same error.

Here is one example of my datasets. 
{
'images': [
	{
	'file_name': 'train_0000.png', 
	'height': 621, 
	'width': 579, 
	'id': 0
	}],

'annotations': [
	{
	'image_id': 0, 
	'bbox': [[109, 324, 38, 52], [49, 228, 31, 55], [162, 179, 39, 101], [180, 378, 16, 42]], 
	'iscrowd': 0, 
	'category_id': 2, 
	'id': 0
	},
	{
	'image_id': 0, 
	'bbox': [[120, 182, 42, 49], [157, 275, 72, 54], [136, 139, 46, 59], [94, 119, 60, 54], [233, 155, 42, 43]], 
	'iscrowd': 0, 
	'category_id': 3, 
	'id': 1
	},
	{
	'image_id': 0, 
	'segmentation': [[473, 81, 278, 80, 280, 278, 183, 278, 181, 323, 278, 327, 278, 520, 475, 519]], 
	'iscrowd': 0, 
	'category_id': 4, 
	'id': 3
	}],

'categories': [
	{'id': 1,  'name': '引戸'}, 
	{'id': 2,  'name': '折戸'}, 
	{'id': 3,  'name': '開戸'}, 
	{'id': 4,  'name': 'LDK'}, 
	{'id': 5,  'name': '廊下'}, 
	{'id': 6,  'name': '浴室'}, 
	{'id': 7,  'name': '洋室'}]
}

**Comment by zylo117** [comment]
I think some of the annotations are missing key 'iscrowd'.

**Comment by Goki-0324** [comment]
Thank you again for the reply.
OK, I'll examine closely.
