### ISSUE TITLE
Input tensor at index 1 has invalid shape [110484, 26], but expected [110484, 3]

### ISSUE THREAD

**Issue by Alan-D-Chen** [zylo117/Yet-Another-EfficientDet-Pytorch#660]
@zylo117 您好，请问您为什么要写一个`CustomDataParallel`函数。我在您的源代码的基础上增加了一个loss function。在多个GPU上运行时就会出现`Input tensor at index 1 has invalid shape [110484, 26], but expected [110484, 3]`，只有在使用一个G PU时才能够运行起来。于是我尝试使用官方的nn.DataParallel替换您的CustomDataParallel，但是还是同样的报错。

热烈期盼您的回复～

**Comment by zylo117** [comment]
CustomDataParallel上有注释啊。强制把输入均匀打散到每个gpu，而不是像dataparallel那样传到gpu0，再传到其他gpu，提速，减少gpu0占用
至于你的问题，可以展示下你修改了哪里吗？不然很难分析

**Comment by Alan-D-Chen** [comment]
好的，谢谢。/Yet-Another-EfficientDet-Pytorch/efficientdet/loss.py 中我并没修改之前的regression_losses代码，但是我增加了新的regression loss function：
```
diou = torch.stack([diou, diou]).mean(dim=0).cuda()
        GIoU = torch.stack([(1-GIoU), (1-GIoU)]).mean(dim=0).cuda()
        return torch.stack(classification_losses).mean(dim=0, keepdim=True), \
               torch.stack(regression_losses).mean(dim=0, keepdim=True) * 50, 0.5*diou, 0.5*GIoU
```
问题症结似乎在return，只要是在return 中加入了0.5*diou, 0.5*GIoU，在使用多个GPU时就会出现以上的报错，但是取消0.5*diou, 0.5*GIoU，在多个或者单个GPU上都可以顺利的运行。
当然，我还修改了positive_indices 的获得方式，是增加了positive_indices其中1 的个数。
lines 93 :
```
IoU, CDIoU, GIoU, positive_indices, IoU_max, IoU_argmax, diou = Tselect_machine(anchor[:, :], bbox_annotation[:, :4])
  '''
            IoU = calc_iou(anchor[:, :], bbox_annotation[:, :4])

            IoU_max, IoU_argmax = torch.max(IoU, dim=1)
        
            #### Multi level selection machine ####
            CDIoU = calc_cdiou(anchor[:, :], bbox_annotation[:, :4])

            CDIoU_max, CDIoU_argmax = torch.max(IoU, dim=1)

            GIoU = calc_giou(anchor[:, :], bbox_annotation[:, :4])

            GIoU_max, GIoU_argmax = torch.max(IoU, dim=1)

            #### The ending of Multi level selection machine ####
            '''
            #### compute the loss for classification  ####
            targets = torch.ones_like(classification) * -1
            # print("type of targets:", type(targets))
            # print("targets.shape:", targets.shape)
            # print("targets:\n", targets)
            if torch.cuda.is_available():
                targets = targets.cuda()
            # Select positive and negative samples #
            # negative samples #
            targets[torch.lt(IoU_max, 0.4), :] = 0

            # positive_indices = torch.ge(IoU_max, 0.5)  # [0,1,0,1,1,0,0,1,1,......]

            num_positive_anchors = positive_indices.sum()  # int(num)
```

**Comment by zylo117** [comment]
看得我一脸懵逼，这是哪一行报错了啊，你又在哪个位置加入的代码？

**Comment by Alan-D-Chen** [comment]
报错是在：/Users/amc/Documents/pycode/Yet-Another-EfficientDet-Pytorch/train.py中的lines 250
`       cls_loss, reg_loss, cdiou_loss, giou_loss = model(imgs, annot, obj_list=params.obj_list)`
这一行报错了。
`[Error] Traceback (most recent call last):
  File "train.py", line 250, in train
    cls_loss, reg_loss, cdiou_loss, giou_loss = model(imgs, annot, obj_list=params.obj_list)
  File "/home/alanc/anaconda3/envs/alans/lib/python3.6/site-packages/torch/nn/modules/module.py", line 727, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/home/alanc/anaconda3/envs/alans/lib/python3.6/site-packages/torch/nn/parallel/data_parallel.py", line 162, in forward
    return self.gather(outputs, self.output_device)
  File "/home/alanc/anaconda3/envs/alans/lib/python3.6/site-packages/torch/nn/parallel/data_parallel.py", line 174, in gather
    return gather(outputs, output_device, dim=self.dim)
  File "/home/alanc/anaconda3/envs/alans/lib/python3.6/site-packages/torch/nn/parallel/scatter_gather.py", line 68, in gather
    res = gather_map(outputs)
  File "/home/alanc/anaconda3/envs/alans/lib/python3.6/site-packages/torch/nn/parallel/scatter_gather.py", line 63, in gather_map
    return type(out)(map(gather_map, zip(*outputs)))
  File "/home/alanc/anaconda3/envs/alans/lib/python3.6/site-packages/torch/nn/parallel/scatter_gather.py", line 55, in gather_map
    return Gather.apply(target_device, dim, *outputs)
  File "/home/alanc/anaconda3/envs/alans/lib/python3.6/site-packages/torch/nn/parallel/_functions.py", line 71, in forward
    return comm.gather(inputs, ctx.dim, ctx.target_device)
  File "/home/alanc/anaconda3/envs/alans/lib/python3.6/site-packages/torch/nn/parallel/comm.py", line 230, in gather
    return torch._C._gather(tensors, dim, destination)
RuntimeError: Input tensor at index 1 has invalid shape [110484, 14], but expected [110484, 50]

Input tensor at index 1 has invalid shape [110484, 14], but expected [110484, 50]
`
但是我修改的部分在loss函数里面

**Comment by Alan-D-Chen** [comment]
不知道我有没有解释清楚，热烈期盼您的回复。🥺🥺

**Comment by Alan-D-Chen** [comment]
😁😁😁😁😁😁😁😁😁😁🥺🥺🥺🥺🥺🥺🥺🥺🥺

**Comment by zylo117** [comment]
这个很难调试惹，是多卡才会发生的情况吧。多卡就会用C库封装了，都不知道在哪里调用了。
但是可以肯定的是，这个故障点出现在你的loss的实现中，自己用print大法看看具体是哪一行翻车吧
