### ISSUE TITLE
关于pytorch使用显存的问题

### ISSUE THREAD

**Issue by re-burn** [zylo117/Yet-Another-EfficientDet-Pytorch#697]
先说一下配置，rtx2080ti，4gpu，前几天训练的时候batch_size最大设置为32都不会爆显存，大概是从周四晚上开始，用跟之前一模一样的数据集和一模一样的模型（就只改了lr，anchors和alpha）结果加载数据的时候就报oom了，把batch_size减小到4以后（也就是一个gpu一张图片）才勉强能训练，但还是会跑到一半报oom，请问大佬这是什么原因呢

**Comment by b-endica** [comment]
[Error] Traceback (most recent call last):
  File "train.py", line 226, in train
    cls_loss, reg_loss = model(imgs, annot, obj_list=params.obj_list)
  File "/root/anaconda3/envs/pytorch/lib/python3.7/site-packages/torch/nn/modules/module.py", line 727, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/root/anaconda3/envs/pytorch/lib/python3.7/site-packages/torch/nn/parallel/data_parallel.py", line 161, in forward
    outputs = self.parallel_apply(replicas, inputs, kwargs)
  File "/root/anaconda3/envs/pytorch/lib/python3.7/site-packages/torch/nn/parallel/data_parallel.py", line 171, in parallel_apply
    return parallel_apply(replicas, inputs, kwargs, self.device_ids[:len(replicas)])
  File "/root/anaconda3/envs/pytorch/lib/python3.7/site-packages/torch/nn/parallel/parallel_apply.py", line 86, in parallel_apply
    output.reraise()
  File "/root/anaconda3/envs/pytorch/lib/python3.7/site-packages/torch/_utils.py", line 428, in reraise
    raise self.exc_type(msg)
RuntimeError: Caught RuntimeError in replica 0 on device 0.
Original Traceback (most recent call last):
  File "/root/anaconda3/envs/pytorch/lib/python3.7/site-packages/torch/nn/parallel/parallel_apply.py", line 61, in _worker
    output = module(*input, **kwargs)
  File "/root/anaconda3/envs/pytorch/lib/python3.7/site-packages/torch/nn/modules/module.py", line 727, in _call_impl
    result = self.forward(*input, **kwargs)
  File "train.py", line 75, in forward
    _, regression, classification, anchors = self.model(imgs)
  File "/root/anaconda3/envs/pytorch/lib/python3.7/site-packages/torch/nn/modules/module.py", line 727, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/root/userfolder/EfficientDet-Pytorch/backbone.py", line 70, in forward
    _, p3, p4, p5 = self.backbone_net(inputs)
  File "/root/anaconda3/envs/pytorch/lib/python3.7/site-packages/torch/nn/modules/module.py", line 727, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/root/userfolder/EfficientDet-Pytorch/efficientdet/model.py", line 449, in forward
    x = block(x, drop_connect_rate=drop_connect_rate)
  File "/root/anaconda3/envs/pytorch/lib/python3.7/site-packages/torch/nn/modules/module.py", line 727, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/root/userfolder/EfficientDet-Pytorch/efficientnet/model.py", line 82, in forward
    x = self._bn1(x)
  File "/root/anaconda3/envs/pytorch/lib/python3.7/site-packages/torch/nn/modules/module.py", line 727, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/root/userfolder/EfficientDet-Pytorch/utils/sync_batchnorm/batchnorm.py", line 88, in forward
    output = (input - _unsqueeze_ft(mean)) * _unsqueeze_ft(inv_std * self.weight) + _unsqueeze_ft(self.bias)
RuntimeError: CUDA out of memory. Tried to allocate 30.00 MiB (GPU 0; 10.76 GiB total capacity; 9.69 GiB already allocated; 7.12 MiB free; 9.74 GiB reserved in total by PyTorch)

**Comment by zylo117** [comment]
这个原因很多，后处理部分可能会有出入，比如threshold过滤出来的anchor越多，内存就用得越多
