### ISSUE TITLE
training error

### ISSUE THREAD

**Issue by kaishijeng** [zylo117/Yet-Another-EfficientDet-Pytorch#7]
My system is ubuntu 18.04 with 1 GPU.
WHen I run the following script:
    python train.py -c 0 --batch_size 4 --data ./data/
I got "the TypeError: forward() takes 2 positional arguments but 5" were given in the error log: below:

loading annotations into memory...
Done (t=7.84s)
creating index...
index created!
loading annotations into memory...
Done (t=0.27s)
creating index...
index created!
initializing weights...
  0%|                                                                                            | 0/29571 [00:00<?, ?it/s]Traceback (most recent call last):
  File "train.py", line 172, in train
    _, regression, classification, anchors = model(imgs)
  File "/home/henry/miniconda3/envs/remnav/lib/python3.6/site-packages/torch/nn/modules/module.py", line 532, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/henry/miniconda3/envs/remnav/lib/python3.6/site-packages/torch/nn/parallel/data_parallel.py", line 150, in forward
    return self.module(*inputs[0], **kwargs[0])
  File "/home/henry/miniconda3/envs/remnav/lib/python3.6/site-packages/torch/nn/modules/module.py", line 532, in __call__
    result = self.forward(*input, **kwargs)
TypeError: forward() takes 2 positional arguments but 5 were given

forward() takes 2 positional arguments but 5 were given
  0%|                                                                                  | 1/29571 [00:00<6:58:07,  1.18it/s]Traceback (most recent call last):
  File "train.py", line 172, in train
    _, regression, classification, anchors = model(imgs)
  File "/home/henry/miniconda3/envs/remnav/lib/python3.6/site-packages/torch/nn/modules/module.py", line 532, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/henry/miniconda3/envs/remnav/lib/python3.6/site-packages/torch/nn/parallel/data_parallel.py", line 150, in forward
    return self.module(*inputs[0], **kwargs[0])
  File "/home/henry/miniconda3/envs/remnav/lib/python3.6/site-packages/torch/nn/modules/module.py", line 532, in __call__
    result = self.forward(*input, **kwargs)
TypeError: forward() takes 2 positional arguments but 5 were given

forward() takes 2 positional arguments but 5 were given
Traceback (most recent call last):
  File "train.py", line 172, in train
    _, regression, classification, anchors = model(imgs)
  File "/home/henry/miniconda3/envs/remnav/lib/python3.6/site-packages/torch/nn/modules/module.py", line 532, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/henry/miniconda3/envs/remnav/lib/python3.6/site-packages/torch/nn/parallel/data_parallel.py", line 150, in forward
    return self.module(*inputs[0], **kwargs[0])
  File "/home/henry/miniconda3/envs/remnav/lib/python3.6/site-packages/torch/nn/modules/module.py", line 532, in __call__
    result = self.forward(*input, **kwargs)
TypeError: forward() takes 2 positional arguments but 5 were given

forward() takes 2 positional arguments but 5 were given

**Comment by zylo117** [comment]
hi, can you show me your torch version?

try pull the latest code from master and  set num_gpu to 0, and run again.

**Comment by kaishijeng** [comment]
My pytorch version:

>>> import torch
>>> torch.__version__
'1.4.0'

My dataset should be correct because I verified print out actual image path during the loading

**Comment by kaishijeng** [comment]
If I use num_gpus 0, it runs with errors.

**Comment by zylo117** [comment]
it is the same error?

can you print or debug the shape of imgs right before line172?

**Comment by kaishijeng** [comment]
printout after line 172:
****image shape torch.Size([4, 3, 512, 512])

I don't use IDE.

**Comment by kaishijeng** [comment]
If I run CPU version, num_gpu=0, it also print out the same shape as gpu:
****image shape torch.Size([4, 3, 512, 512])

**Comment by zylo117** [comment]
OK，it is weird, i just run it with:

python3 train.py -c 0 --batch_size 4

both num_gpu = 4 and 1, it worked alright.

loading annotations into memory...
Done (t=17.83s)
creating index...
index created!
loading annotations into memory...
Done (t=0.54s)
creating index...
index created!
initializing weights...
Step: 20. Epoch: 1/500. Iteration: 21/29571. Cls loss: 29527.66211. Reg loss: 1.70128. Total loss: 29529.36328:   0%|   | 21/29571 [00:44<6:43:55,  1.22it/s]

can you pull the latest code and follow the tutorial then give it a try?

**Comment by kaishijeng** [comment]
Just pull your master branch and run into the Same error.
What python version do you use?
Mine is 3.6.0

**Comment by zylo117** [comment]
can you share your minimal code to replicate this error?

**Comment by zylo117** [comment]
mine is py3.7

**Comment by kaishijeng** [comment]
Why is self.forward of  EfficientDetBackbone in backbone.py not called?
I added a printout in that function and it didn't printout before an error occurs:
    _, regression, classification, anchors = model(imgs)
  File "/home/henry/miniconda3/envs/remnav/lib/python3.6/site-packages/torch/nn/modules/module.py", line 532, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/henry/miniconda3/envs/remnav/lib/python3.6/site-packages/torch/nn/parallel/data_parallel.py", line 150, in forward
    return self.module(*inputs[0], **kwargs[0])
  File "/home/henry/miniconda3/envs/remnav/lib/python3.6/site-packages/torch/nn/modules/module.py", line 532, in __call__
    result = self.forward(*input, **kwargs)
.
Should model(imgs) in train.py call this function before     result = self.forward(*input, **kwargs)
 in torch nn/modules/module.py?

**Comment by zylo117** [comment]
it should, but it seems that you script crashed at  before the arguments pass to EfficientDetBackbone.

ok, I found the problem. I have multiple gpus, that is why I didn't have the problem.

I will fix it soon

**Comment by zylo117** [comment]
ok, the bug should be fixed, can you pull the latest code and try again?

**Comment by kaishijeng** [comment]
Issue is resolved with your fix.
Thanks,

**Comment by kaishijeng** [comment]
I will reopen this issue because I got an error at end of first epoch:

Traceback (most recent call last):
  File "train.py", line 296, in <module>
    train(opt)
  File "train.py", line 231, in train
    _, regression, classification, anchors = model(imgs)
  File "/home/henry/miniconda3/envs/py3k/lib/python3.7/site-packages/torch/nn/modules/module.py", line 532, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/henry/4TB/Yet-Another-Efficient-Pytorch-new/backbone.py", line 71, in forward
    _, p3, p4, p5 = self.backbone_net(inputs)
  File "/home/henry/miniconda3/envs/py3k/lib/python3.7/site-packages/torch/nn/modules/module.py", line 532, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/henry/4TB/Yet-Another-Efficient-Pytorch-new/efficientdet/model.py", line 345, in forward
    x = self.model._conv_stem(x)
  File "/home/henry/miniconda3/envs/py3k/lib/python3.7/site-packages/torch/nn/modules/module.py", line 532, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/henry/4TB/Yet-Another-Efficient-Pytorch-new/efficientnet/utils_extra.py", line 51, in forward
    x = self.conv(x)
  File "/home/henry/miniconda3/envs/py3k/lib/python3.7/site-packages/torch/nn/modules/module.py", line 532, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/henry/miniconda3/envs/py3k/lib/python3.7/site-packages/torch/nn/modules/conv.py", line 345, in forward
    return self.conv2d_forward(input, self.weight)
  File "/home/henry/miniconda3/envs/py3k/lib/python3.7/site-packages/torch/nn/modules/conv.py", line 342, in conv2d_forward
    self.padding, self.dilation, self.groups)
RuntimeError: Input type (torch.FloatTensor) and weight type (torch.cuda.FloatTensor) should be the same

**Comment by kaishijeng** [comment]
I think your previous fix  is only limited to training part.
Now the validation part has same issue after 1st epoch. Can you apply the same fix for validation part?

            if epoch % opt.val_interval == 0:
                model.eval()
                loss_regression_ls = []
                loss_classification_ls = []
                for iter, data in enumerate(val_generator):
                    with torch.no_grad():
                        imgs = data['img']
                        annot = data['annot']

                        if params.num_gpus > 0:
                            annot = annot.cuda()
                        _, regression, classification, anchors = model(imgs)   <-- error occured

**Comment by zylo117** [comment]
ok, working on it

**Comment by zylo117** [comment]
done, it's fixed, sorry for the trouble

**Comment by kaishijeng** [comment]
Thank you for a quick response. Will let you know the status after 1st epoch's traing

**Comment by zylo117** [comment]
the crash is after the checkpoint, you can resume the training from the checkpoint instead of starting again

**Comment by kaishijeng** [comment]
I don't see the crash may be after the checkpoint. Close this issue for now

Thanks,
