### ISSUE TITLE
Help on CSV custom dataset evaluation function

### ISSUE THREAD

**Issue by alancarlosml** [zylo117/Yet-Another-EfficientDet-Pytorch#704]
Hi,

I have a dataset written in CSV like RetinaNet pattern.

I can training with no problems. Also I can make infereces properly.

But, the evaluation function I have made is not working.

I'm getting the following error:

```
(alan_gpu) desktop:~/Documentos/Yet-Another-EfficientDet-Pytorch$ python csv_eval.py --dataset CSV --dataset_root "annotations/multi/test.csv" --labels_csv "annotations/classes_num.csv" -p polipos -c 0 --weight "logs/polipos/efficientdet-d0_98_45000.pth"
Loading checkpoint: logs/polipos/efficientdet-d0_98_45000.pth ...
len(dataset): 612
/home/viplabgpu/anaconda3/envs/alan_gpu/lib/python3.9/site-packages/torch/nn/functional.py:718: UserWarning: Named tensors and all their associated APIs are an experimental feature and subject to change. Please do not use them for anything important until they are released as stable. (Triggered internally at  /opt/conda/conda-bld/pytorch_1623448238472/work/c10/core/TensorImpl.h:1156.)
  return torch.max_pool2d(input, kernel_size, stride, padding, dilation, ceil_mode)
Traceback (most recent call last):
  File "/home/viplabgpu/Documentos/Yet-Another-EfficientDet-Pytorch/csv_eval.py", line 379, in <module>
    evaluate_csv(valid_dataset, model)
  File "/home/viplabgpu/Documentos/Yet-Another-EfficientDet-Pytorch/csv_eval.py", line 256, in evaluate_csv
    all_detections = _get_detections(generator, retinanet, score_threshold=score_threshold, max_detections=max_detections, save_path=save_path)
  File "/home/viplabgpu/Documentos/Yet-Another-EfficientDet-Pytorch/csv_eval.py", line 121, in _get_detections
    image_boxes      = boxes[indices[scores_sort], :]
numpy.core._exceptions.MemoryError: Unable to allocate 4.80 TiB for an array with shape (14, 76725, 4, 76725, 4) and data type float32
```

 Here is the csv_eval.py

```
from __future__ import print_function
import numpy as np
import json
import os
import torch
import argparse
from torchvision import transforms
from dataloader import CSVDataset, collater, Resizer, AspectRatioBasedSampler, Augmenter, Normalizer
import yaml
from backbone import EfficientDetBackbone
from tqdm import tqdm

device = torch.device("cuda" if torch.cuda.is_available() else "cpu")

class Params:
    def __init__(self, project_file):
        self.params = yaml.safe_load(open(project_file).read())

    def __getattr__(self, item):
        return self.params.get(item, None)

def compute_overlap(a, b):
    """
    Parameters
    ----------
    a: (N, 4) ndarray of float
    b: (K, 4) ndarray of float
    Returns
    -------
    overlaps: (N, K) ndarray of overlap between boxes and query_boxes
    """
    area = (b[:, 2] - b[:, 0]) * (b[:, 3] - b[:, 1])

    iw = np.minimum(np.expand_dims(a[:, 2], axis=1), b[:, 2]) - np.maximum(np.expand_dims(a[:, 0], 1), b[:, 0])
    ih = np.minimum(np.expand_dims(a[:, 3], axis=1), b[:, 3]) - np.maximum(np.expand_dims(a[:, 1], 1), b[:, 1])

    iw = np.maximum(iw, 0)
    ih = np.maximum(ih, 0)

    ua = np.expand_dims((a[:, 2] - a[:, 0]) * (a[:, 3] - a[:, 1]), axis=1) + area - iw * ih

    ua = np.maximum(ua, np.finfo(float).eps)

    intersection = iw * ih

    return intersection / ua

def _compute_ap(recall, precision):
    """ Compute the average precision, given the recall and precision curves.
    Code originally from https://github.com/rbgirshick/py-faster-rcnn.
    # Arguments
        recall:    The recall curve (list).
        precision: The precision curve (list).
    # Returns
        The average precision as computed in py-faster-rcnn.
    """
    # correct AP calculation
    # first append sentinel values at the end
    mrec = np.concatenate(([0.], recall, [1.]))
    mpre = np.concatenate(([0.], precision, [0.]))

    # compute the precision envelope
    for i in range(mpre.size - 1, 0, -1):
        mpre[i - 1] = np.maximum(mpre[i - 1], mpre[i])

    # to calculate area under PR curve, look for points
    # where X axis (recall) changes value
    i = np.where(mrec[1:] != mrec[:-1])[0]

    # and sum (\Delta recall) * prec
    ap = np.sum((mrec[i + 1] - mrec[i]) * mpre[i + 1])
    return ap


def _get_detections(dataset, retinanet, score_threshold=0.05, max_detections=100, save_path=None):
    """ Get the detections from the retinanet using the generator.
    The result is a list of lists such that the size is:
        all_detections[num_images][num_classes] = detections[num_detections, 4 + num_classes]
    # Arguments
        dataset         : The generator used to run images through the retinanet.
        retinanet           : The retinanet to run on the images.
        score_threshold : The score confidence threshold to use.
        max_detections  : The maximum number of detections to use per image.
        save_path       : The path to save the images with visualized detections to.
    # Returns
        A list of lists containing the detections for each image in the generator.
    """
    all_detections = [[None for i in range(dataset.num_classes())] for j in range(len(dataset))]

    print('len(dataset):', len(dataset))

    retinanet.eval()
    
    with torch.no_grad():

        for index in range(len(dataset)):
            data = dataset[index]
            scale = data['scale']

            # run network
            features, regression, classification, anchors = retinanet(data['img'].permute(2, 0, 1).to(device).float().unsqueeze(dim=0))

            scores = regression.cpu().numpy()
            labels = classification.cpu().numpy()
            boxes  = anchors.cpu().numpy()

            # correct boxes for image scale
            boxes /= scale

            # select indices which have a score above the threshold
            indices = np.where(scores > score_threshold)[0]
            if indices.shape[0] > 0:
                # select those scores
                scores = scores[indices]

                # find the order with which to sort the scores
                scores_sort = np.argsort(-scores)[:max_detections]

                # select detections
                image_boxes      = boxes[indices[scores_sort], :]
                image_scores     = scores[scores_sort]
                image_labels     = labels[indices[scores_sort]]
                image_detections = np.concatenate([image_boxes, np.expand_dims(image_scores, axis=1), np.expand_dims(image_labels, axis=1)], axis=1)

                # copy detections to all_detections
                for label in range(dataset.num_classes()):
                    all_detections[index][label] = image_detections[image_detections[:, -1] == label, :-1]
            else:
                # copy detections to all_detections
                for label in range(dataset.num_classes()):
                    all_detections[index][label] = np.zeros((0, 5))

            print('{}/{}'.format(index + 1, len(dataset)), end='\r')

    return all_detections


def _get_annotations(generator):
    """ Get the ground truth annotations from the generator.
    The result is a list of lists such that the size is:
        all_detections[num_images][num_classes] = annotations[num_detections, 5]
    # Arguments
        generator : The generator used to retrieve ground truth annotations.
    # Returns
        A list of lists containing the annotations for each image in the generator.
    """
    all_annotations = [[None for i in range(generator.num_classes())] for j in range(len(generator))]

    for i in range(len(generator)):
        # load the annotations
        annotations = generator.load_annotations(i)

        # copy detections to all_annotations
        for label in range(generator.num_classes()):
            all_annotations[i][label] = annotations[annotations[:, 4] == label, :4].copy()

        print('{}/{}'.format(i + 1, len(generator)), end='\r')

    return all_annotations

def evaluate_csv(
    generator,
    retinanet,
    iou_threshold=0.5,
    score_threshold=0.5,
    max_detections=100,
    save_path=None
):
    """ Evaluate a given dataset using a given retinanet.
    # Arguments
        generator       : The generator that represents the dataset to evaluate.
        retinanet           : The retinanet to evaluate.
        iou_threshold   : The threshold used to consider when a detection is positive or negative.
        score_threshold : The score confidence threshold to use for detections.
        max_detections  : The maximum number of detections to use per image.
        save_path       : The path to save images with visualized detections to.
    # Returns
        A dict mapping class names to mAP scores.
    """

    # gather all detections and annotations

    all_detections = _get_detections(generator, retinanet, score_threshold=score_threshold, max_detections=max_detections, save_path=save_path)
    all_annotations = _get_annotations(generator)

    average_precisions = {}

    for label in range(generator.num_classes()):
        false_positives = np.zeros((0,))
        true_positives = np.zeros((0,))
        scores = np.zeros((0,))
        num_annotations = 0.0

        for i in range(len(generator)):
            detections = all_detections[i][label]
            annotations = all_annotations[i][label]
            num_annotations += annotations.shape[0]
            detected_annotations = []

            for d in detections:
                scores = np.append(scores, d[4])

                if annotations.shape[0] == 0:
                    false_positives = np.append(false_positives, 1)
                    true_positives = np.append(true_positives, 0)
                    continue

                overlaps = compute_overlap(
                    np.expand_dims(d, axis=0), annotations)
                assigned_annotation = np.argmax(overlaps, axis=1)
                max_overlap = overlaps[0, assigned_annotation]

                if max_overlap >= iou_threshold and assigned_annotation not in detected_annotations:
                    false_positives = np.append(false_positives, 0)
                    true_positives = np.append(true_positives, 1)
                    detected_annotations.append(assigned_annotation)
                else:
                    false_positives = np.append(false_positives, 1)
                    true_positives = np.append(true_positives, 0)

        # no annotations -> AP for this class is 0 (is this correct?)
        if num_annotations == 0:
            average_precisions[label] = 0, 0
            continue

        # sort by score
        indices = np.argsort(-scores)
        false_positives = false_positives[indices]
        true_positives = true_positives[indices]

        # compute false positives and true positives
        false_positives = np.cumsum(false_positives)
        true_positives = np.cumsum(true_positives)

        # compute recall and precision
        recall = true_positives / num_annotations
        precision = true_positives / \
            np.maximum(true_positives + false_positives,
                       np.finfo(np.float64).eps)

        # compute average precision
        average_precision = _compute_ap(recall, precision)
        average_precisions[label] = average_precision, num_annotations
    
    print('\nmAP:')
    MAP = 0
    for label in range(1, generator.num_classes()):
        label_name = generator.label_to_name(label)
        MAP = average_precisions[label][0]
        precision = precision[-1]
        recall = recall[-1]
        f1 = 2 * (precision * recall)/(precision + recall)
        
        print('{}: {}'.format(label_name, average_precisions[label][0]))
        print("precision: ", precision)
        print("recall: ", recall)
        print("f1: ", f1)
    
    return average_precisions, MAP

if __name__ == '__main__':

    parser = argparse.ArgumentParser(description='EfficientDet Training With Pytorch')
    #train_set = parser.add_mutually_exclusive_group()
    parser.add_argument('--dataset', default='CSV', choices=['VOC', 'COCO', 'CSV'], type=str, 
                        help='VOC, COCO or CSV')
    parser.add_argument('--dataset_root', default='',
                        help='Dataset root directory path [/root/data/VOCdevkit/, /root/data/coco/, /root/data/csv/]')
    parser.add_argument('--labels_csv', default='', 
                        help='Path to class labels')
    parser.add_argument('-p', '--project', type=str, default='coco', 
                        help='project file that contains parameters')
    parser.add_argument('-c', '--compound_coef', type=int, default=0, 
                        help='coefficients of efficientdet')
    parser.add_argument('--weight', default='./checkpoint_VOC_efficientdet-d0_248.pth', type=str,
                        help='Checkpoint state_dict file to resume training from')
    args = parser.parse_args()

    params = Params(f'projects/{args.project}.yml')

    if(args.weight is not None):
        resume_path = str(args.weight)
        print("Loading checkpoint: {} ...".format(resume_path))
        args.num_class = 2
        model = EfficientDetBackbone(num_classes=args.num_class, compound_coef=args.compound_coef,
                                 ratios=eval(params.anchors_ratios), scales=eval(params.anchors_scales))
        model.load_state_dict(torch.load(args.weight), strict=False)

    model = model.cuda()
    if(args.dataset == 'VOC'):
        valid_dataset = VOCDetection(root=args.dataset_root, image_sets=[('2007', 'test')],
                                     transform=transforms.Compose([Normalizer(), Resizer()]))
        evaluate(valid_dataset, model)
    elif(args.dataset == 'COCO'):
        valid_dataset = CocoDataset(root_dir=args.dataset_root, set_name='val2017',
                                    transform=transforms.Compose([Normalizer(), Resizer()]))
        evaluate_coco(valid_dataset, model)
    elif(args.dataset == 'CSV'):
        valid_dataset = CSVDataset(train_file=args.dataset_root, class_list=args.labels_csv, 
                                    transform=transforms.Compose([Normalizer(), Resizer()]))
        evaluate_csv(valid_dataset, model)
```

Can anybody help me?

**Comment by zylo117** [comment]
I think you should convert to coco style json first
