### ISSUE TITLE
json.decoder.JSONDecodeError: Expecting ',' delimiter: line 1 column 76546049 (char 76546048)

### ISSUE THREAD

**Issue by fumingheng** [zylo117/Yet-Another-EfficientDet-Pytorch#72]
Traceback (most recent call last):
  File "train.py", line 338, in <module>
    train(opt)
  File "train.py", line 116, in train
    Resizer(input_sizes[opt.compound_coef])]))
  File "/content/drive/My Drive/EfficientDet/Yet-Another-EfficientDet-Pytorch/efficientdet/dataset.py", line 17, in __init__
    self.coco = COCO(os.path.join(self.root_dir, 'annotations', 'instances_' + self.set_name + '.json'))
  File "/usr/local/lib/python3.6/dist-packages/pycocotools/coco.py", line 84, in __init__
    dataset = json.load(open(annotation_file, 'r'))
  File "/usr/lib/python3.6/json/__init__.py", line 299, in load
    parse_constant=parse_constant, object_pairs_hook=object_pairs_hook, **kw)
  File "/usr/lib/python3.6/json/__init__.py", line 354, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python3.6/json/decoder.py", line 339, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python3.6/json/decoder.py", line 355, in raw_decode
    obj, end = self.scan_once(s, idx)
json.decoder.JSONDecodeError: Expecting ',' delimiter: line 1 column 76546049 (char 76546048)

**Comment by zylo117** [comment]
obiviously your json is corrupted

**Comment by fumingheng** [comment]
Thanks, I downloaded it again.It worked.
