### ISSUE TITLE
训练时出现错误

### ISSUE THREAD

**Issue by zhangxiaohuixuhao** [zylo117/Yet-Another-EfficientDet-Pytorch#85]
您好，
       数据使用的COCO2014，环境使用的是cuda9.0，pytorch1.1，在进行3.c训练时，报错如下：
 [Error] Traceback (most recent call last):
  File "train.py", line 221, in train
    cls_loss, reg_loss = model(imgs, annot, obj_list=params.obj_list)
  File "/home/zhanghui/anaconda3/envs/efficientdet/lib/python3.6/site-packages/torch/nn/modules/module.py", line 493, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/zhanghui/anaconda3/envs/efficientdet/lib/python3.6/site-packages/torch/nn/parallel/data_parallel.py", line 148, in forward
    inputs, kwargs = self.scatter(inputs, kwargs, self.device_ids)
  File "/DATA/zhanghui/EfficientDet/Yet-Another-EfficientDet-Pytorch/utils/utils.py", line 185, in scatter
    for device_idx in range(len(devices))], \
  File "/DATA/zhanghui/EfficientDet/Yet-Another-EfficientDet-Pytorch/utils/utils.py", line 185, in <listcomp>
    for device_idx in range(len(devices))], \
RuntimeError: Source tensor must be contiguous.
期待您的回答，感谢！！！

**Comment by zylo117** [comment]
update to pytorch 1.4

**Comment by LIUHAO121** [comment]
change num_gpus = 1 in yaml files

**Comment by zhangxiaohuixuhao** [comment]
谢谢回答，非常感谢，升级成1.4之后是可以用多块GPU运行的，若环境限制只能使用低版本的pytorch，可以yml文件中的num_gpus改成一块
