### ISSUE TITLE
Expected object of scalar type Double but got scalar type Float for argument #3 'mat1' in call to _th_addmm_

### ISSUE THREAD

**Issue by dosemeion** [zylo117/Yet-Another-EfficientDet-Pytorch#92]

**Comment by dosemeion** [comment]
[Error] Traceback (most recent call last):
  File "C:/Users/dosemeion/Desktop/Object Detection/Code/EfficientDet/Yet-Another-EfficientDet-Pytorch-master/train.py", line 225, in train
    cls_loss, reg_loss = model(imgs, annot.long(), obj_list=params.obj_list)
  File "C:\Users\dosemeion\Anaconda3\envs\pt13\lib\site-packages\torch\nn\modules\module.py", line 532, in __call__
    result = self.forward(*input, **kwargs)
  File "C:/Users/dosemeion/Desktop/Object Detection/Code/EfficientDet/Yet-Another-EfficientDet-Pytorch-master/train.py", line 75, in forward
    _, regression, classification, anchors = self.model(imgs)
  File "C:\Users\dosemeion\Anaconda3\envs\pt13\lib\site-packages\torch\nn\modules\module.py", line 532, in __call__
    result = self.forward(*input, **kwargs)
  File "C:\Users\dosemeion\Desktop\Object Detection\Code\EfficientDet\Yet-Another-EfficientDet-Pytorch-master\backbone.py", line 65, in forward
    _, p3, p4, p5 = self.backbone_net(inputs)
  File "C:\Users\dosemeion\Anaconda3\envs\pt13\lib\site-packages\torch\nn\modules\module.py", line 532, in __call__
    result = self.forward(*input, **kwargs)
  File "C:\Users\dosemeion\Desktop\Object Detection\Code\EfficientDet\Yet-Another-EfficientDet-Pytorch-master\efficientdet\model.py", line 399, in forward
    x = self.model._conv_stem(x)
  File "C:\Users\dosemeion\Anaconda3\envs\pt13\lib\site-packages\torch\nn\modules\module.py", line 532, in __call__
    result = self.forward(*input, **kwargs)
  File "C:\Users\dosemeion\Desktop\Object Detection\Code\EfficientDet\Yet-Another-EfficientDet-Pytorch-master\efficientnet\utils_extra.py", line 51, in forward
    x = self.conv(x)
  File "C:\Users\dosemeion\Anaconda3\envs\pt13\lib\site-packages\torch\nn\modules\module.py", line 532, in __call__
    result = self.forward(*input, **kwargs)
  File "C:\Users\dosemeion\Anaconda3\envs\pt13\lib\site-packages\torch\nn\modules\conv.py", line 345, in forward
    return self.conv2d_forward(input, self.weight)
  File "C:\Users\dosemeion\Anaconda3\envs\pt13\lib\site-packages\torch\nn\modules\conv.py", line 342, in conv2d_forward
    self.padding, self.dilation, self.groups)
RuntimeError: Expected object of scalar type Double but got scalar type Float for argument #3 'mat1' in call to _th_addmm_

**Comment by zylo117** [comment]
update to pytorch 1.4

**Comment by dosemeion** [comment]
> 更新到pytorch 1.4
I have updated it, but the error still occurs

**Comment by zylo117** [comment]
what modifications did you make?
it's the original clone of the latest code?
can you run the tutorial without errors?

**Comment by dosemeion** [comment]
> what modifications did you make?
> is it the original clone of the latest code?
> can you run the tutorial without errors?

The demo can run, and code is up to date
modify：
1.CocoDataset → VOCDetection
2.follow efficientdet-signatrix:
for iter, data in enumerate(progress_bar):
imgs = data['img']
annot = data['annot']
→ for iter, (images, annotations) in enumerate(progress_bar):
imgs = images
annot = annotations

**Comment by dosemeion** [comment]
> what modifications did you make?
> is it the original clone of the latest code?
> can you run the tutorial without errors?
sorry,  I made a mistake
