### ISSUE TITLE
Input type (torch.cuda.DoubleTensor) and weight type (torch.cuda.FloatTensor) should be the same

### ISSUE THREAD

**Issue by dosemeion** [zylo117/Yet-Another-EfficientDet-Pytorch#94]
[Error] Traceback (most recent call last):
  File "C:/Users/dosemeion/Desktop/Object Detection/Code/EfficientDet/Yet-Another-EfficientDet-Pytorch-master/train.py", line 227, in train
    cls_loss, reg_loss = model(imgs, annot, obj_list=params.obj_list)
  File "C:\Users\dosemeion\Anaconda3\envs\pt14\lib\site-packages\torch\nn\modules\module.py", line 532, in __call__
    result = self.forward(*input, **kwargs)
  File "C:/Users/dosemeion/Desktop/Object Detection/Code/EfficientDet/Yet-Another-EfficientDet-Pytorch-master/train.py", line 75, in forward
    _, regression, classification, anchors = self.model(imgs)
  File "C:\Users\dosemeion\Anaconda3\envs\pt14\lib\site-packages\torch\nn\modules\module.py", line 532, in __call__
    result = self.forward(*input, **kwargs)
  File "C:\Users\dosemeion\Desktop\Object Detection\Code\EfficientDet\Yet-Another-EfficientDet-Pytorch-master\backbone.py", line 65, in forward
    _, p3, p4, p5 = self.backbone_net(inputs)
  File "C:\Users\dosemeion\Anaconda3\envs\pt14\lib\site-packages\torch\nn\modules\module.py", line 532, in __call__
    result = self.forward(*input, **kwargs)
  File "C:\Users\dosemeion\Desktop\Object Detection\Code\EfficientDet\Yet-Another-EfficientDet-Pytorch-master\efficientdet\model.py", line 401, in forward
    x = self.model._conv_stem(x)
  File "C:\Users\dosemeion\Anaconda3\envs\pt14\lib\site-packages\torch\nn\modules\module.py", line 532, in __call__
    result = self.forward(*input, **kwargs)
  File "C:\Users\dosemeion\Desktop\Object Detection\Code\EfficientDet\Yet-Another-EfficientDet-Pytorch-master\efficientnet\utils_extra.py", line 51, in forward
    x = self.conv(x)
  File "C:\Users\dosemeion\Anaconda3\envs\pt14\lib\site-packages\torch\nn\modules\module.py", line 532, in __call__
    result = self.forward(*input, **kwargs)
  File "C:\Users\dosemeion\Anaconda3\envs\pt14\lib\site-packages\torch\nn\modules\conv.py", line 345, in forward
    return self.conv2d_forward(input, self.weight)
  File "C:\Users\dosemeion\Anaconda3\envs\pt14\lib\site-packages\torch\nn\modules\conv.py", line 342, in conv2d_forward
    self.padding, self.dilation, self.groups)
RuntimeError: Input type (torch.cuda.DoubleTensor) and weight type (torch.cuda.FloatTensor) should be the same

Input type (torch.cuda.DoubleTensor) and weight type (torch.cuda.FloatTensor) should be the same

Process finished with exit code -1

modify model.py:  
add the code before ‘x = self.model._conv_stem(x)’
x = x.type(torch.FloatTensor)
x = x.cuda()

right? but it can run.

**Comment by zylo117** [comment]
So I guess you are using your own dataloader which generate DoubleTensor, but it should be FloatTensor
